### ISSUE TITLE
Covering the .something and .something() syntax

### ISSUE THREAD

**Issue by tobyhodges** [swcarpentry/python-novice-gapminder#10]
There is a section titled "Built-in Functions (and Methods) and Help". Is this where we would introduce Python dot-something syntax and discuss attributes and methods? It should definitely happen here if not before, and feeds nicely into looking at help pages etc.

**Comment by jdidion** [comment]
This is a good question - at what point to you introduce the concept of classes and objects. I believe understanding the very basics of object-oriented programming is critical to understanding python, even if the student will only ever use objects in built-in or third-party libraries and never write their own, and is also a prerequisite to teaching about accessing object members.

Another important question is whether, when, and how to introduce the concept of a module. The relationship between class, module, and library can be hard to grok (I know I had trouble with it), but I think it's important to be able to understand and use the precise terminology. These concepts can be naturally explained using a tree structure without having to go into actual implementation details - the student just needs to learn that they move from one level of the tree to the next by joining "branches" with a ".". This can lead nicely into discussing the important abstraction of "everything in python is an object." (Or maybe it's better to teach this the other way around - but in any case, the concepts are tightly coupled). Finally, this can be synthesized with the student's earlier learning about functions to show that executable members of objects can be called by using the same syntax - just add parentheses (and, optionally, arguments).

I suggest that section 6 be renamed to something like "Libraries > Modules > Classes > Objects."
