### ISSUE TITLE
HTML pages missing resources, incorrect links

### ISSUE THREAD

**Issue by lonsbio** [swcarpentry/python-novice-gapminder#102]
Assets missing and incorrect links at http://swcarpentry.github.io/python-novice-gapminder/

Possibly related to recent change to `page.root`? 451f696812972331fa54661eae43f404056435cf

**Comment by gvwilson** [comment]
Thanks - forgot to define the correct variable in `_config.yml`. Fixed in fd7e9ff - can you please confirm?

**Comment by lonsbio** [comment]
Looks good!
