### ISSUE TITLE
Should all challenges include solutions?

### ISSUE THREAD

**Issue by leouieda** [swcarpentry/python-novice-gapminder#110]
I've been looking at the lesson challenges and some have solutions while others don't. Is this by design or something that is waiting to be done?

**Comment by gvwilson** [comment]
All challenges should have solutions - it would be great if you could 
fill some in.
Thanks,
Greg

**Comment by alee** [comment]
Closing for now in favor of more fine grained issues targeting the lessons still lacking challenge solutions
