### ISSUE TITLE
Suggested Edit: Libraries.md

### ISSUE THREAD

**Issue by afrahshafquat** [swcarpentry/python-novice-gapminder#112]
A quick exercise to install non-standard libraries (e.g. pandas, matplotlib etc.) might be necessary to add in the lesson, as there is an entire section on pandas dataframe manipulation

**Comment by gvwilson** [comment]
Cool - will you be able to submit something as part of your instructor training checkout? Thanks, Greg

**Comment by ThomasA** [comment]
It seems like this suggestion might not be relevant anymore. The current version of the Python lesson recommends installing Anaconda and as far as I can see, Pandas and Matplotlib should be included out-of-the-box.

**Comment by eldobbins** [comment]
Yes, this is true.  We just taught a Workshop and didn't need to install either Pandas or Matplotlib separately.

Can this issue be closed?
