### ISSUE TITLE
Are the variable names in the Swapping Values exercise in Episode 2 confusing?

### ISSUE THREAD

**Issue by lo5an** [swcarpentry/python-novice-gapminder#114]
During a workshop today, I put the code for the Swapping Values exercise from Episode 2 up on the screen and asked a small group to talk through it.

They guessed that we were doing something temperature related, which kind of derailed their thinking, and that made me wonder if the collocation of `highest`, `lowest`, and `temp` isn't a little unfortunate. 

Maybe something like

``` python
x = 1.0
y = 3.0
swap = x
x = y
y = swap
```

would be a little clearer?

**Comment by tbekolay** [comment]
I agree, `swap` would be much better in this case.

**Comment by alee** [comment]
fixed in c683a2b1b469232a46b9419cbca99811de5101b6
