### ISSUE TITLE
docker jekyll server

### ISSUE THREAD

**Issue by alee** [swcarpentry/python-novice-gapminder#120]
I set up docker-compose and a simple Dockerfile to make a docker container that can run Jekyll and serve the site. This helps me test my changes to any content before submitting a pull request without having to install jekyll on my local machine. 

If this seems beneficial, I'd be happy to make a pull request with instructions on the README and the associated docker files. This does require that you install [docker engine](https://docs.docker.com/engine/installation/) and [docker compose](https://docs.docker.com/compose/install/).

For a preview of what Docker integration would look like, https://github.com/alee/python-novice-gapminder/commit/7dff37345ae5db5b36767162866a505afc2abe88

**Comment by ntmoore** [comment]
This sounds like it would be useful.  Do you have a running example?

**Comment by alee** [comment]
Hey Nathan,

I just submit a running example that you can test by checking out the referenced PR (or my branch at https://github.com/alee/python-novice-gapminder/tree/docker).

**Comment by alee** [comment]
Closing this for now, something like this should be raised with the styles template group since it applies to all lessons
