### ISSUE TITLE
Add how to add an image in Markdown example?

### ISSUE THREAD

**Issue by weaverbel** [swcarpentry/python-novice-gapminder#151]
When I demo markdown, people often want to know how easy it is to include an image - maybe show that as well as showing them how to add a link and use the other simple formatting?

This is in the first bit: https://swcarpentry.github.io/python-novice-gapminder/01-run-quit/

**Comment by ntmoore** [comment]
I think this could make for a good exercise, eg, show basic code for image inclusion and then have the exercise of (for example) including alt text, salacing, linking the image to something external, etc.

**Comment by weaverbel** [comment]
Great thanks @ntmoore - and great to have this lesson in the offing ! We are teaching it in Brisbane.
