### ISSUE TITLE
Plotting introduces loops before loops lesson

### ISSUE THREAD

**Issue by amandamiotto** [swcarpentry/python-novice-gapminder#162]
In https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/_episodes/09-plotting.md

You have a loop before you talk about what a loop is.
Also works with lists before explaining lists.

Maybe move this lesson to just after the loops lesson? Not a huge thing but worth mentioning.

**Comment by vahtras** [comment]
I agree completely, my first impression of this lesson is that there is an overall problem with ordering of the sections, like having the most basic parts (lists,  for-loops and if-statements) towards the end of the lesson.

**Comment by timothylwarren** [comment]
I posted issue #296 earlier today before seeing this issue. I suggest an alternative to fix the problem. Short version of my suggestion is that there is no need to use for loops or lists if columns in original csv data file are years not 'gdp_xxx' strings.

**Comment by eldobbins** [comment]
This issue seems to have been resolved.  At least, I cannot find any loops in the current version of Lesson 9.

**Comment by timothylwarren** [comment]
I agree that the issue seems to be resolved in current lesson, which has changed significantly throughout.

**Comment by alee** [comment]
thanks for double checking, @timothylwarren @eldobbins !
