### ISSUE TITLE
Use DC-ecology image of indexes to explain slices

### ISSUE THREAD

**Issue by djinnome** [swcarpentry/python-novice-gapminder#168]
Data carpentry does a good job of explaining slices using this figure:
http://www.datacarpentry.org/python-ecology-lesson/fig/slicing-indexing.svg

I recommend doing the same for the variables section that explains slicing and indexing

**Comment by echism** [comment]
sent https://github.com/swcarpentry/python-novice-gapminder/pull/439

**Comment by eldobbins** [comment]
This issue seems to have been solved by the PR above.  Can it be closed?
