### ISSUE TITLE
Jupyter only accept one language per notebook

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-gapminder#175]
http://swcarpentry.github.io/python-novice-gapminder/01-run-quit/ says

> this format allows Jupyter to mix software (in several languages) with documentation and graphics, all in one file.

But the statement isn't 100% true because on Jupyter Notebook the kernel/language is associate with the notebook itself and not with the cell.

Can we change the statement to

>  this format allows Jupyter to mix source code, text and images, all in one file.

**Comment by mzc9** [comment]
May I take a stab at this?

**Comment by alee** [comment]
Absolutely! 👍
