### ISSUE TITLE
"Define a new function" missing from "Learners Will Be Able To..."

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/python-novice-gapminder#18]
The [goals](https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/index.md#goals) include writing modular code with no duplication, the [learners will know](https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/index.md#learners-will-know) "The difference between defining and calling a function", and there is a lesson on [writing functions](https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/index.md#writing-functions). However, the ability to write a function is not listed under the skills that [learners will be able to](
https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/index.md#learners-will-be-able-to) accomplish at the end of the lesson.

**Comment by gvwilson** [comment]
Good catch - fixed in 931353c
