### ISSUE TITLE
Improve variable names

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-gapminder#181]
In http://swcarpentry.github.io/python-novice-gapminder/02-variables/ we have 

> Variable names:
> - cannot start with a digit
> - cannot contain spaces, quotation marks, or other punctuation
> - may contain an underscore (typically used to separate words in long variable names)

What about simplify it using

> Variable names:
> - can **only** contain letters, digit and underscore, `_`
> - can not start with a digit

**Comment by alee** [comment]
fixed in c9e9b3173c8b8981ea3cbc8ab72a0bad73573c1d
