### ISSUE TITLE
String delimiter

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-gapminder#183]
Python accepts single or double quotations as string delimiter. And [PEP8](https://www.python.org/dev/peps/pep-0008/) says

> In Python, single-quoted strings and double-quoted strings are the same. This PEP does not make a recommendation for this. 

I think that we should replace

> To add a string to the printout, wrap the string in single quotations.

with

> To add a string to the printout, wrap the string in single or double quotations.

in http://swcarpentry.github.io/python-novice-gapminder/02-variables/.

**Comment by vphill** [comment]
Made a stab at this suggestion in #290
