### ISSUE TITLE
Language when talking about integer and floating point

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-gapminder#190]
In http://swcarpentry.github.io/python-novice-gapminder/03-types-conversion/ we have

> - Integer (int): counting numbers like 3 or -512.
> - Floating point number (float): fractional numbers like 3.14159 or -2.5.
>   - Integers are used to count, floats are used to measure.

Could we replace it with

> - Integer (int): represents numbers like 3 or -512.
> - Floating point number (float): represents numbers like 3.14159 or -2.5.

Is wrong to say that floating point number store fractions because 1/3 can't be stored for example. And I think the "Integers are used to count, floats are used to measure." is unnecessary.

**Comment by ntmoore** [comment]
integers are used to measure as well.  "For how many days should I take these antibiotics?"  Easy PR for new folks.
