### ISSUE TITLE
Missing solution for the Jigsaw Puzzle challenge

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-gapminder#196]
In http://swcarpentry.github.io/python-novice-gapminder/06-libraries/ the challenge "Jigsaw Puzzle (Parson’s Problem) Programming Example" doesn't have a solution.

**Comment by jtsmith2** [comment]
Should this challenge be deleted?  A solution for the same problem (selecting a random base from a list) is actually given in the solution to the challenge directly above it.

**Comment by ntmoore** [comment]
Not deleted as there is use in having multiple ways to ask a question.
