### ISSUE TITLE
Over use of print function

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-gapminder#206]
Why do the lesson make extensive use of the `print` function? For example, in http://swcarpentry.github.io/python-novice-gapminder/07-reading-tabular/ we could have

~~~
data.columns
~~~

instead of

~~~
print(data.columns)
~~~

The output in this case is exactly the same.

![screenshot_2017-06-16_13-51-42](https://user-images.githubusercontent.com/1506457/27227364-1962c33a-529b-11e7-896c-f1bcfacc13e3.png)

**Comment by tobyhodges** [comment]
This is a valid question. But I would say that the answer depends on how reliant you want the material be on working in a notebook or REPL. What I mean is, people who start to write Python scripts may leave the lesson thinking that they don't need `print()` to print an object. Or they may become confused when they try to execute a cell containing two lines e.g.

```
data.index
data.columns
```

and only see the 'output' of the second line (though I confess that this may already be covered earlier in the lesson). Explicitly including `print()` when we want something output from a cell is good practice in my opinion, even if requires annoying extra keystrokes. It helps me to be able to extract the code and run it as a script with minimal processing.

**Comment by rgaiacs** [comment]
> What I mean is, people who start to write Python scripts may leave the lesson thinking that they don't need print() to print an object.

I see this as a minor issue but happy to explore it more.

> Or they may become confused when they try to execute a cell containing two lines e.g.

This is covered by the layout. If you want to show the value of two "variables" you should use

~~~
> ~~~
> data.index
> ~~~
> {: python}
> ~~~
> 10
> ~~~
> {: output}
> ~~~
> data.columns
> ~~~
> {: python}
> ~~~
> 5
> ~~~
> {: output}
~~~

to indicate for the reader that they need to use two cells.

>  It helps me to be able to extract the code and run it as a script with minimal processing.

I would say this is another issue with the Python lesson. :-( I **REALLY** wish to be able to use knitr to build the lesson.
