### ISSUE TITLE
Make it clear which sections most classes do or don't reach

### ISSUE THREAD

**Issue by BillMills** [swcarpentry/python-novice-gapminder#21]
This is great work, I'm really keen for to teach this lesson! I do however think the time estimates are too short across the board; marching through this in a straight line will maybe get through functions by the end of a day. People have raised concerns in the past about feeling disappointed they didn't get through all the material; as I always say, it's fine if you don't finish - but given that this seems to stress people out, maybe frame that material as an appendix / supplement to signal that flexibility.

**Comment by iglpdc** [comment]
I agree with @BillMills. I mentioned somewhere that we should explicitly mention that it's ok not to finish and that we should not set expectations hard to fulfill.

I would like to have a guide to tell instructors what to drop (be challenges, topics, or examples) in case things go south.

**Comment by gvwilson** [comment]
> I would like to have a guide to tell instructors what to drop (be 
challenges, topics, or examples) in case things go south.

So would I - the trick is getting people to give us the information we 
need to construct it...

**Comment by iglpdc** [comment]
> So would I - the trick is getting people to give us the information we
need to construct it...

Yes,  this is really hard to get. I was thinking more in what you would teach if the lesson was not 6 hours, but 3 or 4. Maybe by providing these two points, instructors could adapt better during workshops and we would normalize situations in which not all the material is covered.

**Comment by gvwilson** [comment]
Closed by 35b7550
