### ISSUE TITLE
Missing Splitting-Applying-Combining episode

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-gapminder#210]
The lesson is missing a episode about splitting-applying-combining, see http://pandas.pydata.org/pandas-docs/stable/groupby.html.

**Comment by ntmoore** [comment]
I think this would be a good addition.  It could certainly be a sub section in lesson #8, https://swcarpentry.github.io/python-novice-gapminder/08-data-frames/

**Comment by alee** [comment]
added in 52c2d6d629155489b959a978162e216242fb7e12 

feedback / followup in #276
