### ISSUE TITLE
13-looping-data-sets.md missing from syllabus in rendered version of code

### ISSUE THREAD

**Issue by pfujita** [swcarpentry/python-novice-gapminder#218]
---
Hello!

Looking at the rendered version of this set of lessons, the 13th episode (13-looping-data-sets.md) is not displaying in the schedule/syllabus here: 

https://swcarpentry.github.io/python-novice-gapminder/

I looked at the code, but am not sure why this is happening, so I'm submitting a bug report rather than a fix (sorry!).

Hope this helps!

Pauline
---

**Comment by delocalizer** [comment]
should be fixed by #222

**Comment by ntmoore** [comment]
This seems to be resolved. Thanks for pointing it out and correcting it!
