### ISSUE TITLE
Teach Markdown notation for writing documentation throughout

### ISSUE THREAD

**Issue by davis68** [swcarpentry/python-novice-gapminder#23]
Along with programming style, instructors should *implicitly* teach students Markdown notation when writing {pseudocode, comments, docstrings}—and *explicitly* emphasize consistency and parallel phrasing and structure (modularity) in writing the same.  Could go straight in the checklist.

Starting the habit early can only help.

**Comment by gvwilson** [comment]
But docstrings use ReStructured Text rather than Markdown, don't they?

**Comment by davis68** [comment]
Governing documentation:

- https://www.python.org/dev/peps/pep-0257/  <= no syntax specified
- https://www.python.org/dev/peps/pep-0287/  <= supersedes with RST syntax

Looks like a very-low-level discussion persists among Markdown fans, but
you're right—RST carries the day.
