### ISSUE TITLE
Some comments on your very nice work

### ISSUE THREAD

**Issue by justbennet** [swcarpentry/python-novice-gapminder#24]
Greg,

I think all the topics are useful and germane to the audience.  The only things I might add or remove are 1) Lists and iterables are such a central part of Python, they almost have to be talked about somehow (suggestions below).  I see nothing on _writing_ data files, and I think most people will want to be able to save results.  This looks really good.  Please let me know if you have fleshed out sections to review, and I'll find time to help, if my comments are on-topic and helpful.

Under Essential Questions, clarify what you mean by "process multiple data sets".  Coming from statistics, that could be each file treated indendently, or it could imply merging multiple files into a single data set with an indicator and then doing a stratified analysis.  Both would be valuable to demonstrate.

I think that, this being Python, that covering iteration in some way is almost required.  This could be introduced with file handles and reinforced with loops, maybe?  Yes, I see that you explicitly say NOT lists.  But they are such an integral part of the python way.

Might I suggest introducing writing functions with 'templates' -- That includes the docstring, the __init__, a test, and a dummy function that assigns a variable and prints its value.  Once the docstring is written, that is used as the guide for writing the real functionality.  I don't do this consistently enough, but I think my code gets written faster, I resist feature creep better, and it's easier to do it this way than to decode already written code.  I think it also helps encourage comments in the code.  Like an outline for a term paper.

Which are the key SciPy modules?

**Comment by gvwilson** [comment]
Decomposed into #36, #37, #38, and #39.
