### ISSUE TITLE
Text formatting in Lists episode

### ISSUE THREAD

**Issue by celticelk** [swcarpentry/python-novice-gapminder#245]
Starting with the output of the second example in the "Appending items to a list lengthens it" section, the text formatting of the code vs. instruction sections has gotten inverted, so that the instruction sections appear as code and vice-versa; this extends up to the first exercise in that episode.

**Comment by alee** [comment]
This appears to be fixed now:

http://swcarpentry.github.io/python-novice-gapminder/11-lists/#appending-items-to-a-list-lengthens-it
