### ISSUE TITLE
Introduce pylab method of matplotlib?

### ISSUE THREAD

**Issue by NihanPol** [swcarpentry/python-novice-gapminder#248]
Would it be a good idea to introduce the pylab version of plotting here (currently I only see inline plotting)? I feel that it would be a good idea to introduce this concept for continuously updating plots without having to invoke plt.show() and could be useful for some people who need dynamic plots.

**Comment by djinnome** [comment]
If I understand the issue correctly, then I agree with the problem, but not with the solution, if by pylab version of plotting, you mean generating plots outside the jupyter notebook.

My recommendation instead would be to replace
the old-school magic command
%matplotlib inline

with the more modern magic command:

%matplotlib notebook

This will enable dynamic and continuously updatable plots within the notebook.

**Comment by NihanPol** [comment]
Yes, that is exactly what I meant. I thought the magic command was simply %pylab, but maybe I'm wrong.

Also, the pop-up windows in which plots are generated are, in themselves, really powerful tools to manipulate the plots produced, so they might give a GUI way of manipulating plots, in addition to the python scripting.

Cheers,

**Comment by djinnome** [comment]
I agree that pop-up windows can be very powerful tools, but for the purpose of teaching within the constraints of a software carpentry workshop, I am concerned  it will introduce a new host of potential issues to debug in realtime when the plots are not displayed within the notebook.  (Why aren't my plots displaying?  Do I not have the right backend installed, or is it the plot just hiding behind my browser? )

Based on the [documentation](http://ipython.readthedocs.io/en/stable/interactive/magics.html), the magic command:

%pylab notebook

should enable dynamic pylab charts within the jupyter notebook, but I would need to test it to be sure.

**Comment by NihanPol** [comment]
I guess that is true. I still think it would be worth mentioning, even if in passing, by the instructor. Something along the lines of "Hey you can also plot using this device and you would have more customizability...".
But I completely agree with what you say :)

PS: I tried out using both %pylab notebook and %matplotlib notebook, and both work the same way.
