### ISSUE TITLE
Add Socrative Quizzes for real-time assessment

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/python-novice-gapminder#25]
I think it would be nice to make a Socrative question for all the short exercise questions so that the instructor can administer the exercise and get realtime feedback on learner responses. 

Pros: 
1. It can help keep the time devoted to each question very manageable because the instructor can see student correct and incorrect answers. 
2. We can collecting data on what students are learning and how effective the lesson is. 
3. We can see which exercises the instructors chose to administer. Given how many people think fewer exercises are better, this could be some very valuable data.

**Comment by alistairwalsh** [comment]
That would be awesome! I have tried to incorporate [Socrative](http://www.socrative.com/) into past lessons but found it time consuming to create from scratch. Having questions ready to go would have been great.

**Comment by philrosenfield** [comment]
This could also allow for MCQs to be validated. Our assumptions on what their incoming misconceptions are or how clearly the questions are written can be tested with enough MCQ answers.
