### ISSUE TITLE
First plot in Lesson 09 is of meaningless data. Maybe should be a time-series to align with objective.

### ISSUE THREAD

**Issue by evankielley** [swcarpentry/python-novice-gapminder#265]
Instructor Training

RE: http://swcarpentry.github.io/python-novice-gapminder/09-plotting/

I think the first plot should align more with the objective (making a time-series plot) or at least represent something physical.

**Comment by ntmoore** [comment]
Please feel free to suggest (via a pull request) some other data to plot. "Minutes after 8am" and "number of people in the workshop room" might be fun but we don't have a workshop in the near future for me to take this data.

**Comment by ntmoore** [comment]
Most of the interesting data sets (eg, money vs happiness, money vs problems, price of cheddar cheese vs amt of years aged, etc) is fairly time-consuming to type out.  I agree with you that compelling datasets are compelling, but they have to be easy to type.  If you have one in mind, please submit a PR.
