### ISSUE TITLE
Suggest replacing `typeof` with `class` in episode 4

### ISSUE THREAD

**Issue by davebridges** [swcarpentry/python-novice-gapminder#268]
In lesson **04-data-structures-part1**, under data types the user learns using `typeof` to determine the structure of data.  This can be confusing because the `typeof` of a factor returns an _integer_ not a _factor_ as one might expect.   I suggest modifying this lesson to use `class` instead which returns a data type of factor.  This may be less confusing to the new learner.  For example:

```{r}
>cats <- data.frame(coat = c('calico','black','tabby'))
>class(cats$coat)
[1] "factor"
>typeof(cats$coat)
[1] "integer"
```

**Comment by djinnome** [comment]
Hi Dave, I think you have intended to post to the R novice gapminder. This is the python novice gapminder.

**Comment by davebridges** [comment]
oh you are right, sorry
