### ISSUE TITLE
Use Bokeh for plotting instead of Matplotlib

### ISSUE THREAD

**Issue by benlaken** [swcarpentry/python-novice-gapminder#27]
Matplot lib is so 2002 - if you want to give the students a 'wow' feeling and teach them the new normal how about Bokeh? 

I would say the library is becoming mature now, currently at 0.11, and to make nice-looking high-level interactive plots the interface is very simple. At least no more cognitive load than starting with matplotlib in my opinion. Plus, if you are already planning on Pandas (which I fully +1) this already ties in perfectly to Bokeh, which understands how to deal with pandas objects. 

You could use the code here from the Bokeh Gapminder example (https://anaconda.org/bokeh/gapminder/notebook) to perhaps create a simpler version for the lesson. (Without some of the formatting, the background year text, and the legend, it could be simple-ish, and perhaps even still have the slider widget and hover tool?) 

If that is more for an intermediate to advanced level, you could use grid-plot to show a couple of snap-shots in time from the dataset, rendering them together with linked axes and a hover tool (quite easy in Bokeh). See grid plot examples here http://bokeh.pydata.org/en/0.10.0/docs/user_guide/layout.html

**Comment by jiffyclub** [comment]
- matplotlib was started around 2002 and continues to be actively developed and supported
- many of our audience are going to need to generate figures for journals and as far as I know that's not possible with Bokeh
- a lot of people (some of them active in Software Carpentry) have and continue to put a lot of work into matplotlib and I think it deserves a bit more respect than this rude dismissal

**Comment by mwaskom** [comment]
- matplotlib "understands how to deal with pandas objects":

```
plt.scatter(x="total_bill", y="tip", data=tips)
```
![image](https://cloud.githubusercontent.com/assets/315810/13019556/02304090-d185-11e5-93ad-a6c0ba634b11.png)

**Comment by benlaken** [comment]
Of course no 'dis' to matplotlib, it is certainly the go-to plot library and is great. Until recently it was the main library for my published figures. Its style is often compared to Matlab, which is an old language. And I would say that its high level plots aren't enough without adding a fair bit of extra tweaks to publish - hence the popularity of packages like Seaborne. But I certainly think its safe to say that it is one of the final evolutions of packages for traditional plots though. 

So after the push-back I should clarify that I think Bokehs features are more future oriented, and new people will be more excited in bokeh relative to matplotlib as, for virtually the same amount of code as in Matplotlib, they can create a notebook/web-oriented figure that lets them interact with the data. Perhaps more of a thrill for a new user to unlock that knowledge.

**Comment by tobyhodges** [comment]
I'm a fan of Bokeh and use it often, and even included it in another lesson introducing Python to people with no previous experience of programming. But for SWC's intended audience I think that is is more useful to introduce a library that can be used to produce figures for publication. Using Bokeh, one can't create vector graphics, which places a limit on its usefulness in this regard. 

Also, for people who enjoy total control over how a figure looks, the "fair bit of extra tweaks" that you refer to are something to be appreciated!

**Comment by alistairwalsh** [comment]
The pandas plotting with seaborn is quite presentable. 
I agree that our audience is heading toward publication. But there is a long way to go between a beginner workshop and producing publication quality plots so I think it's ok to consider all graphics libraries - Boken included. The intermediate Python lessons should look at the deeper issues of plotting in Python 
If the lesson design was up to me, for the beginner course, I would choose to use the Pandas plotting capabilities and avoid introducing the greater matplotlib ecosystem or the Boken world. I don't have anything against those libraries but we already have a tool loaded that can produce really nice exploratory plots.
Hope I've appreciated everyone's point of view and made the reasons for my own opinion clear. :-)

**Comment by gvwilson** [comment]
I'd be grateful if someone who knows more about plotting than I do could look at `_episodes/12-plotting.md` and adjust it to be Pandas-only - there's still some raw matplotlib in there (I think).

**Comment by alee** [comment]
I think the point about a scientific audience and publication quality figures is an important one; as I understand it, bokeh is primarily targeted at browser-based visualization (although the [scientific publication of the future](http://www.scientificpaperofthefuture.org/gpf/) may well be a first-class web citizen).

I'm going to close this issue, but please feel free to reopen if you think it's worth pursuing.

Part of the reason for this is the discussion in #405 and we may consider creating a choose-your-own-plotting-library path that lets you go with matplotlib or plotnine or even bokeh if so desired.
