### ISSUE TITLE
error in answers to exercise "Locating the Right Module"

### ISSUE THREAD

**Issue by wikfeldt** [swcarpentry/python-novice-gapminder#278]
in episode 6, exercise "Locating the Right Module", two of the answers are
```
from random import randrange
random_index = random.randrange(len(bases))
print(bases[random_index])
```
and 
```
from random import randrange
print(bases[random.randrange(len(bases))])
```
in both cases, it should say `randrange` instead of `random.randrange` inside the print function

**Comment by souravsingh** [comment]
Hmm, Looks like a mistake
Would you be willing to send a PR?

**Comment by wikfeldt** [comment]
sure
