### ISSUE TITLE
Writing lesson material & exercises

### ISSUE THREAD

**Issue by tobyhodges** [swcarpentry/python-novice-gapminder#28]
This is in reference to Greg's blog post ["Designing Lessons Collaboratively"](http://software-carpentry.org/blog/2016/02/designing-lessons-collaboratively.html).

I like the idea of throwing the lesson design open, to however many volunteers there are to write individual sections, based on the plan outline. Of course, this runs the risk of lacking continuity, consistency, and common themes. My hope would be that the established lesson outline, and agreed use of a dataset (the GapMinder data), would provide focus and mitigate against this.

Speaking as a newly-badged instructor, I'd be very happy to contribute exercises to the lesson. Perhaps volunteer instructors could be assigned (or choose) one or more sections to write an exercise for? If there are enough willing volunteers, this could provide overlapping coverage, ensuring multiple exercises for each section/topic.

**Comment by nsoontie** [comment]
I'm willing to help out in writing parts of the lesson too. I like the idea of instructors contributing to different sections/exercises based on an outline. Once the lesson is complete, we could go over and try to improve the continuity and style.

**Comment by alistairwalsh** [comment]
I think being able to choose from a whole range of exercise would be great. The ones that don't get done in the workshop are there if the student wants more practice post workshop.

How much should the lesson material be a script to be read word for word? Or should it be more of a point by point guide that the instructor can fill with their own examples? I think there are advantages with both approaches. 

I know I relied on the script of the original Python beginner lessons for the first few times I delivered it. Now i think I have my own examples and ways of explaining it that resonate with me and I use the code blocks and challenges as prompts for what students need to know at that point.

**Comment by tobyhodges** [comment]
Was a decision ever made on this? If I want to contribute to the lesson material, should I just start writing and submitting PRs? Or do we need further discussion on timing, content etc? Would love to help get this lesson up and running!

**Comment by gvwilson** [comment]
I'm planning to send mail to 'discuss' on Monday asking for one final 
round of comments on the overall schedule, and then we can start to go 
to town.

Thanks,
Greg

**Comment by tobyhodges** [comment]
Great stuff - thanks Greg!
