### ISSUE TITLE
Bug BBQ, April 12-13

### ISSUE THREAD

**Issue by ntmoore** [swcarpentry/python-novice-gapminder#281]
I will be available on April 13 to help PR's submitted via the Bug BBQ for this lesson.  Please feel free to work on issues or submit unrelated PR's!  Not sure if @souravsingh  or @alee will be available during this period?

**Comment by alee** [comment]
I'll be around also, :+1:

**Comment by souravsingh** [comment]
I will also be around for the bug BBQ.
