### ISSUE TITLE
Switching csv columns of gdp data to years ('1957') from longer string ('gdpPercap_1957')

### ISSUE THREAD

**Issue by timothylwarren** [swcarpentry/python-novice-gapminder#296]
As part of instructor training, I've been reviewing the lesson for potential places to contribute.

One thing I've noticed is that in its current form, the 'Plotting' section seems conflicted about how to plot the years on the horizontal axis. In the initial examples, the plots use the original data frame column label 'gdpPercap_xxxx' where 'xxxx' is year (e.g. 1956) and rotates tick labels. In the later plots, the years themselves are plotted. But to extract the years, the lesson appends to a list in a for loop though loops and lists haven't been taught yet. There is a different method proposed in the section to extract years using the strip() method, though I'm not sure this method been introduced.
years = data.columns.str.strip('gdpPercap_')

I think it would be ideal to plot years from the beginning and a simple solution could be to start with a csv file that has the columns labeled as years (i.e. '1957'. 1962') not ('gdpPercap_1957','gdpPercap_1962'). In addition to making plotting more straightforward, it could also benefit the 'Reading Tabular Data into DataFrames' and 'Pandas DataFrames' sections by reducing text clutter and typing burden on instructor
This line
print(data.loc['Italy':'Poland', 'gdpPercap_1962':'gdpPercap_1972'])
becomes
print(data.loc['Italy':'Poland', '1962':'1972'])

To emphasize that the data are gdp data we could name the DataFrame 'gdp_data' instead of 'data'.

If this sounds worthwhile, I could work on this and submit a pull request.

**Comment by timothylwarren** [comment]
As stopgap temporary solution, I submitted pull request #302  which reorders plotting episode so as not to mention for loops or lists

**Comment by riwoodward** [comment]
I agree that this is currently confusing and note that the code provided doesn't give the same plots for me as shown in the images (the x tick labels, which appear partly cropped in the lesson, do not appear at all for me).

I've submitted a PR which brings forward @timothylwarren's code to extract year from the column heading string, and updated the plots accordingly. Please see PR #307 - for my attempt to resolve this.

**Comment by eldobbins** [comment]
I think this issue is solved in the current version of Lesson 9.  In fact, I think the solution is very clever and well documented in the code block for `Plot data directly from a Pandas dataframe.`

Can we close this issue?
