### ISSUE TITLE
Link to errors lesson is broken

### ISSUE THREAD

**Issue by mbonsma** [swcarpentry/python-novice-gapminder#298]
In the [Variables and Assignment](https://swcarpentry.github.io/python-novice-gapminder/02-variables/) lesson, there's a reference to learning about errors which will be covered later. The link points to page that doesn't exist. Perhaps it should link to this page instead, which does cover errors: https://swcarpentry.github.io/python-novice-gapminder/15-scope/

Here's the offending line in the md file:
```
*   We will look at error messages in detail [later]({{ page.root }}/05-error-messages/).
```

**Comment by souravsingh** [comment]
Thanks for the report @mbonsma. Would you be willing to make a PR fixing the issue?
