### ISSUE TITLE
move for loop / list exercises from plotting episode 9 to for loops episode 12

### ISSUE THREAD

**Issue by alee** [swcarpentry/python-novice-gapminder#304]
These will be removed after #302 is merged - see diff at 

https://github.com/swcarpentry/python-novice-gapminder/pull/302/files

**Comment by davidrpugh** [comment]
@alee this issue appears to have been resolved. Can it be closed?

**Comment by alee** [comment]
I think we still need to add the accumulator exercise to Episode 12 actually (all the removed lines in https://github.com/swcarpentry/python-novice-gapminder/commit/ce7d70448dfd42fb51c3ef097bef3e1465637eae)

**Comment by davidrpugh** [comment]
I took a look at the accumulator pattern code that was deleted in Lesson 9.  I don't think we should encourage the use of the accumulator pattern to solve the particular problem of getting a list of years. The Pandas idiomatic way to accomplish this is what we already demonstrate in Lesson 9.
```python
# Instead of for loop we can use pandas dataframe functions to get the year.
years = data.columns.str.strip('gdpPercap_')
```
The only change I would advocate is a slight formatting change to [emphasize the method chaining](https://towardsdatascience.com/the-unreasonable-effectiveness-of-method-chaining-in-pandas-15c2109e3c69)
```python
years = (data.columns
                      .str
                      .strip('gdpPercap_'))
```
