### ISSUE TITLE
Parson's problem simplification in lesson 6

### ISSUE THREAD

**Issue by mikemhenry** [swcarpentry/python-novice-gapminder#309]
The solution to  the Jigsaw Puzzle (Parson’s Problem) Programming Example "Rearrange the following statements so that a random DNA base is printed" is convoluted. I think a more simplified way of answering the question would be:

```
import math
import random
bases = "ACTTGCTTGAC"
n_bases = len(bases)
idx = random.randrange(0, n_bases)
print("random base ", bases[idx])
```

That way students will see less new functions in this example, as `random.randrange` is introduced in the example above. This is my proposed improvement to the parson's problem as well:

```
bases="ACTTGCTTGAC"
import math
import random
___ = random.randrange(0, n_bases)
___ = len(bases)
print("random base ", bases[])
___ = len(bases)
```

I've submitted a  PR #308 to implement these changes, but I would like to discus them as well.

**Comment by alee** [comment]
Thanks for looking into this! As a minor nitpick, `random.randrange(n_bases)` is the same as `random.randrange(0, n_bases)`. We could simplify even further and use [random.choice](https://docs.python.org/3/library/random.html#random.choice) too, the immediately preceding challenge `Locating the Right Module` should probably list that as well..

I get that we are trying to get learners to reinforce their understanding of `len` and character indexing that was introduced in episode 2 + finding and importing libraries, but it feels a bit contrived when something in the standard library exists that does the exact thing that is needed. Perhaps the Parsons problem could have as a requirement printing both the randomly selected base and its index in the string? That at least necessitates the creation of a random index into the string via `randrange` or `nextint`

**Comment by mikemhenry** [comment]
That is a good point!

```
import math
import random
bases = "ACTTGCTTGAC"
n_bases = len(bases)
idx = random.randrange(n_bases)
print("random base ", bases[idx], "base index", idx)
```

```
bases="ACTTGCTTGAC"
import math
import random
___ = random.randrange(0, n_bases)
___ = len(bases)
print("random base ", bases[], "base index, ___)
___ = len(bases)
```

How does that look? I'll also change the lesson text to reflect "print random base and index of the base".

**Comment by alee** [comment]
Sounds good, thanks! @souravsingh already merged your PR but feel free to open a new one
