### ISSUE TITLE
Jupyter Install Changes: python-novice-gapminder/_episodes/01-run-quit.md 

### ISSUE THREAD

**Issue by lsabburg** [swcarpentry/python-novice-gapminder#322]
With the install of Jupyter Notebooks through Anaconda (in Windows), the set PATH checkbox is no longer a default (see image). This means that '$ jupyter notebook' no longer works under this default installation. Either this needs to be mentioned and shown how to fix (add PATH), or we need to only use icon for opening software and not the shell.

![jupyter](https://user-images.githubusercontent.com/34112474/40596344-88b2e13c-627d-11e8-8c6a-fdd17af31675.png)

**Comment by davidrpugh** [comment]
I also noticed this change when teaching and had the students use the icon for opening the software and not the shell. I did not like the idea of encouraging new Python learners to check an optional installation box that is explicitly mentioned as "Not recommended".

**Comment by davidrpugh** [comment]
Will the `conda` command be automatically detected if the "Add Anaconda to my PATH variable" is not checked when installing on Windows?

**Comment by vahtras** [comment]
I am pretty sure that conda will only be detected in the Anaconda console where PATH is set to the install directory

**Comment by alee** [comment]
This should be addressed via https://github.com/swcarpentry/python-novice-gapminder/pull/435
