### ISSUE TITLE
Add instructions on saving figures to "Plotting" lesson

### ISSUE THREAD

**Issue by gaurav** [swcarpentry/python-novice-gapminder#325]
The [*Plotting* lesson](https://swcarpentry.github.io/python-novice-gapminder/09-plotting/) currently ends by creating various plots using `matplotlib.pyplot`. I think this lesson should end with instructions on saving the figures to disk as images using [`matplotlib.pyplot.savefig`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.savefig.html). This would allow students to see how Jupyter Notebook can help them get from input data to images they could use in their papers and publications, and provides a sense of completion at the end of this set of data ingest/plotting lessons before turning back to the subsequent lessons learning about how to use [Python lists](https://swcarpentry.github.io/python-novice-gapminder/11-lists/), [for loops](https://swcarpentry.github.io/python-novice-gapminder/12-for-loops/) and so on.

**Comment by souravsingh** [comment]
+1 on the suggestion.

**Comment by vahtras** [comment]
+1

**Comment by souravsingh** [comment]
@gaurav Would you be willing to create a PR for the issue?

**Comment by gaurav** [comment]
@souravsingh I'd rather not -- I'm not very familiar with PyPlot, so I'm not sure if I can provide the best or most idiomatic way of exporting from it, and I don't know if there are any Jupyter tricks I should use in the export. Besides, this does make a good first issue for new contributors! However, if nobody's done anything about this in a month or so, let me know and I'll give it a stab?

**Comment by souravsingh** [comment]
Fixed in #331. Closing
