### ISSUE TITLE
Add link to Python graph gallery

### ISSUE THREAD

**Issue by vpejaver** [swcarpentry/python-novice-gapminder#329]
Adding a link to the Python graph gallery to the fourth bullet in the "Key Points" section may enable learners to go explore other plot styles and try them out. To keep things less confusing, I would restrict the link to [matplotlib plots](https://python-graph-gallery.com/matplotlib/) but I see no reason why we can't link to the [main page](https://python-graph-gallery.com/).

**Comment by vahtras** [comment]
Yes, please submit a PR. I would welcome a link from the first bullet point to the Matplotlib [home page](matplotlib.org)
