### ISSUE TITLE
SVG versions of diagrams of chapter 9

### ISSUE THREAD

**Issue by CaptainSifff** [swcarpentry/python-novice-gapminder#349]
Dear maintainers,
currently all diagrams obtained from matplotlib are rendered using PNG. I intend to work/have worked
on regenerating them as SVG files. I will submit a separate pull request later on.
Note, that this will also form my contribution as part of the instructor checkout process.

**Comment by ntmoore** [comment]
Thanks for this idea!

Are svg files easily viewed on windows machines?  When I last checked (~ 1.5 years ago) you had to download a special plugin to view svg in Windows 8/10.  Windows is something like 80% of the desktop market so we can't move into an image that doesn't work in that architecture...  https://en.wikipedia.org/wiki/Usage_share_of_operating_systems

I'm not trying to be harsh in this reply!  Please educate me if these images are trivial to view on a windows desktop!

Along the lines of your suggestion, it might be useful to have (in the matplotlib section of the lesson) a short discussion or exercise relating to how one might render a plot as png, pdf, svg, etc file format.

Looking forward to your contribution!

**Comment by CaptainSifff** [comment]
Good question, I just checked on my girlfriends laptop (Win10 + FireFox) and there were no issues. I assumed that since other carpentries lessons already did this: https://github.com/swcarpentry/python-novice-inflammation and e.g. https://github.com/swcarpentry/shell-novice/tree/gh-pages/fig this question has been settled in favour of SVG. In regard to your suggestion of adding something on explaining it...
There is already a comment in the source of chapter 9 explaing it and some arguments against it...
