### ISSUE TITLE
Link in "Writing Functions" Episodes returns 404

### ISSUE THREAD

**Issue by zencore** [swcarpentry/python-novice-gapminder#356]
There is a link in the "Writing Functions" episode that returns a 404.

The link description is: "every function returns something", which tries to find  [https://swcarpentry.github.io/04-built-in/](https://swcarpentry.github.io/04-built-in/), which does not exist.

Is this material still available somewhere (maybe: [https://v4.software-carpentry.org/python/func.html](https://v4.software-carpentry.org/python/func.html)), or should the link be removed?

**Comment by alee** [comment]
Link in http://swcarpentry.github.io/python-novice-gapminder/14-writing-functions/index.html

should point to http://swcarpentry.github.io/python-novice-gapminder/04-built-in/index.html (I believe)

**Comment by DSLituiev** [comment]
seems like the link is working and the issue is resolved. 
Maybe it's time to close it?

**Comment by zencore** [comment]
Looks good to me 👍

Thanks for checking up on this @alee and @DSLituiev.
