### ISSUE TITLE
Explain how to write data files (as well as read them)

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/python-novice-gapminder#36]
From #24:

>  I see nothing on writing data files, and I think most people will want to be able to save results.

**Comment by tobyhodges** [comment]
Would like to create a PR for this. Where should it go? At the moment, the only references to reading data that I grep are in 08_reading_tabular.md (pandas only) and 19_defensive.md. Should we only introduce how to write (tabular) files with pandas in section 8? Or should I add `open()` in somewhere?

**Comment by gvwilson** [comment]
Let's stick to just writing tabular files - it can be an exercise in 
section 8.
Cheers,
Greg
