### ISSUE TITLE
Include a brief section on plotting for poor vision and colorblindness?

### ISSUE THREAD

**Issue by anzelpwj** [swcarpentry/python-novice-gapminder#365]
Hi everyone,

I didn't see any mention of this in closed issues, please accept my apologies if this has already been covered before.

If I had a nickle for every plot I've seen at scientific conferences with the text too small or color-choices that would be unreadable to anyone with red-green colorblindness, I'd probably at least be able to get a cheap coffee.

Would it be worth having a brief call-out that people know to use `fontsize`/`labelsize` to change text size, `linewidth` to increase line size, `s` to increase scatterplot marker size, and to make sure not to encode information solely in color? We could also include a link to a few color-blindness simulators ([example 1](https://www.color-blindness.com/coblis-color-blindness-simulator/), [example 2](https://colororacle.org/)) for people to try.

Let me know!
Paul

**Comment by anzelpwj** [comment]
Another useful resource: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833

**Comment by vahtras** [comment]
I think it is a great initiative!
Olav

**Comment by anzelpwj** [comment]
Sounds good! I'll try to draft something within the next couple of days!

**Comment by anzelpwj** [comment]
Sorry this took me a bit longer to get to than I planned - family obligations. PR is here: https://github.com/swcarpentry/python-novice-gapminder/pull/372

**Comment by ntmoore** [comment]
I think this issue is closed.
