### ISSUE TITLE
Teach how to convert an integer to a string 

### ISSUE THREAD

**Issue by ashleychampagne** [swcarpentry/python-novice-gapminder#379]
In this lesson, we learn that you can use a slice to get a substring and that "Numbers are not stored in the written representation, so they can’t be treated like strings." However, what about adding a short follow up to this part of the assignment to teach the students how to convert an integer to a string? For example, if you type in the code: 

a = str(123)
print(a[1])

instead of the code in the lesson: 
a = 123
print(a[1])

...you'll no longer get an error message. 
I think this is important because he teaches how to work through error messages.

**Comment by alee** [comment]
Thanks for the feedback! I agree - would you be willing to submit a PR that adds that text to the solution for [this challenge](http://swcarpentry.github.io/python-novice-gapminder/02-variables/index.html#challenge)? We're getting ready for a lesson release in June and it'd be nice to include.

**Comment by alee** [comment]
Also wanted to add that I find the statement "Numbers aren't stored in the written representation" to be fairly confusing. Perhaps it would be more clear to say something like 

> Numbers are not strings or sequences and Python will raise an error if you try to perform an index operation on a number. If you want the Nth digit of a number you can convert it into a string and then perform an index operation on that string.

**Comment by whunter** [comment]
Hi, I'm going through the issues here as part of the checkout process looking for things to contribute to. It looks to me as though this issue has been addressed and could be closed.
https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/_episodes/02-variables.md#challenge

**Comment by eldobbins** [comment]
This issue seems to have been solved by the commit on Jun 4, 2019.  It should be closed.

**Comment by alee** [comment]
fixed in 80103adfd59f566c7283e9e01eff875604f961ca
