### ISSUE TITLE
Learners confused about creating new notebooks

### ISSUE THREAD

**Issue by djhoese** [swcarpentry/python-novice-gapminder#395]
I have a coworker who was walking through these lessons to get an idea of python. She was confused pretty early on in "Running and Quitting" because it tells the reader how to start the jupyter server and then shows a screenshot of an open notebook. However, the reader hasn't been told how to create a new notebook yet so their screen (browser window showing the jupyter file browser) does not look like the screenshot. The instructions for creating a notebook are after the screenshot.

I'm not sure if this is worth changing since these lessons are typically taught by an instructor, but it is a little confusing for anyone reading the lessons on their own. I thought I'd at least start the discussion.

**Comment by vahtras** [comment]
Thanks for pointing this out! You are most welcome to suggest an improvement as a PR.

**Comment by davidrpugh** [comment]
This confusion might be mitigated by a switch to JupyterLab as the primary UI. See issue #397  and PR #398.

**Comment by alee** [comment]
@djhoese would you be so kind as to forward the new JupyterLab changes on episode 1 from @davidrpugh to your colleague and see if it helped? We can close this issue if it seems like it's been addressed (or is marginally better)

**Comment by djhoese** [comment]
I'll speak for my colleague and say that the JLab changes cover the original confusion. The screenshots match what the learner sees when following the instructions (`jupyter lab`) so I'd say this is solved.
