### ISSUE TITLE
Use JupyterLab instead of Jupyter notebook as UI

### ISSUE THREAD

**Issue by davidrpugh** [swcarpentry/python-novice-gapminder#397]
I am opening this issue to start a discussion on the costs and benefits of switching from Jupyter notebook to [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) as the UI for the Python lessons. Primary reasons for doing so...

* JupyterLab is the next phase of the evolution of the Jupyter Notebook and as such a switch will probably be desirable at some point.
* JupyterLab functionality and feel is closer to Rstudio functionality and feel which narrows gap between the user experience for Python and R users.

I teach these Python lessons 4-6 times per year at KAUST and over the summer will be developing a version of the lessons that uses JupyterLab instead of Jupyter Notebooks.  I would like to contribute these changes back to the community if there is interest.

**Comment by slel** [comment]
+1 -- earlier this week it occurred to me this should be discussed.

**Comment by davidrpugh** [comment]
I have opened PR #398 with a first draft of changes that include JupyterLab as the primary UI. Feedback is much appreciated!

**Comment by djinnome** [comment]
I went ahead and had my students run jupyter lab for the last lesson I taught. It mostly went well, but I did run into some issues (especially when installing extensions. Navigating a large notebook without the Table of Contents extension is really inconvenient.  Also, the gist extension doesn't work on jupyterlab, and that is really convenient for publishing your notebooks so others can see it).  If you ever need to revert from jupyter lab back to notebooks, all you need to do is change the url from `localhost:8888/lab` to `localhost:8888/notebook`

**Comment by alee** [comment]
Thanks for the PR and issue! I haven't kept up with the evolution of Project Jupyter but reading through https://towardsdatascience.com/jupyter-lab-evolution-of-the-jupyter-notebook-5297cacde6b makes this seem like a good move overall to future proof the lesson.

**Comment by davidrpugh** [comment]
@djinnome at this point I would not advocate exposing learners to jupyter lab extensions.  Currently in the lessons we are encouraging learners to install the Anaconda python distribution to avoid them having to use `conda` or `pip` to install individual packages or extensions. I think it would only make sense to explicitly cover package installation via `conda` or `pip` before asking learners to install jupyter lab extensions.

**Comment by Carreau** [comment]
> revert from jupyter lab back to notebooks, all you need to do is change the url from `localhost:8888/lab` to `localhost:8888/notebook`

Or "help" menu, "open classic notebook", which is easier for student to remember.

> @djinnome at this point I would not advocate exposing learners to jupyter lab extensions.

I would agree; especially since installing an extension could downgrade your JupyterLab. 

Remember that JupyterLab is still not in 1.0; So some minor modification could happen – but that's also a point where feedback from novices to the JupyterLab team is still possible and welcome.
