### ISSUE TITLE
Requirements - developing environment

### ISSUE THREAD

**Issue by ttimbers** [swcarpentry/python-novice-gapminder#4]
What about using Rodeo instead of the Notebook or editing nano? I have heard great things, and it looks very similar to RStudio (which works quite well for teaching). One issue to be aware of is that installing Rodeo and having it work with the Anaconda Python distribution we ask learners to download requires editing the PATH. We don't want to ask learners to do this, so we need to come up with some sort of installer to smooth this out.

**Comment by ttimbers** [comment]
Also, if we are using Rodeo (or something like that) we could skip the last section (Jupyter Notebook) and shave 35 min off of the lesson.

**Comment by lexnederbragt** [comment]
The environment/editor question is a tough one, and I don't think there is an optimal solution. All of them have quite a bit of cognitive load (running a script file requires the shell, as Greg wrote, Jupyter notebook has (too) many functionalities that will confuse learners). Anaconda comes with sypder, which I have a tried a little bit and like - it puts small warning signs in the margin if there is a syntax error, for example.  Rodeo may be a good alternative, but will take time to become comfortable - there are two windows for python commands, one of them is IPython, not python, etc. One advantage is that learners may have seen, or will see, Rstudio, making the Rodeo/Rstudio combo a recognisable duo of environments.

Do we know what instructors are using, especially those that do not use Jupyter? Worth asking them?

**Comment by gvwilson** [comment]
I struggled to get Rodeo working with Anaconda on my Mac three months 
ago, and tripped over some minor glitches, but I'd be very happy if 
that's improved - has anyone on this thread tried it out recently?

**Comment by lexnederbragt** [comment]
I don't remember when I installed it, but I have Rodeo 0.2.4 on MAC OS X Yosemity (10.10.5) and it works through Chrome.

**Comment by lexnederbragt** [comment]
Here is another option: with python comes IDLE (on my mac `/Users/username/anaconda/bin/idle`). Starting IDLE gives a interactive python session (shell), with the possibility to open a separate window for a script, save the script and execute it in the shell. A bit clumsy, but it works for getting everyone started. Once learners are comfortable with it, they can switch to spyder (comes with Anaconda), textwrangler (MAC) or something similar?

**Comment by gvwilson** [comment]
People have complained about IDLE's user interface ever since it was 
created, and we can't ask Data Carpentry participants to run things from 
the shell.  And I just tried launching Spyder with Python 2.7 / Anaconda 
- it hangs on my Mac as soon as I try to edit a file, possibly because 
it can't import something called 'hashtable' which I can't be bothered 
to try to track down.  Does TextWrangler support in-editor execution?

**Comment by lexnederbragt** [comment]
>Does TextWrangler support in-editor execution?

Yes - but I think it is MAC only...

**Comment by gvwilson** [comment]
*sigh* Why can't everyone just use VMS? Now *there* was an operating 
system...

**Comment by gvwilson** [comment]
I spoke with @tracykteal and we decided that the Notebook was the best option (at least for version 1).
