### ISSUE TITLE
Binder button for README

### ISSUE THREAD

**Issue by davidrpugh** [swcarpentry/python-novice-gapminder#404]
Any interest in adding [Binder](https://mybinder.org/) button to the README file which when clicked would open a cloud environment with all software installed for learners to work through the lessons? If so I would be happy to open a PR...

**Comment by djinnome** [comment]
This is really an excellent idea.  I do this for all the lessons I teach, nowadays.
The only question is how much of the lesson do we expose?  On one extreme, we could just present blank notebooks,
on the other extreme, we could have the full lesson available, including quiz questions and solutions, but with the cell outputs empty.

intermediate to this, we could just present a skeleton notebook with only markdown cells, and then we livecode all the code cells

+1

**Comment by alee** [comment]
agreed! I think this would be a great addition.

**Comment by vahtras** [comment]
great!

**Comment by davidrpugh** [comment]
I have open PR #406 that implements the simplest possible solution that might possibly work. I just added an `environment.yml` file that installs Python 3.7 and most recent version of Anaconda and then added the binder button to the README file.

**Comment by davidrpugh** [comment]
Following merge of #423 and #425 we now have a working Binder instance!
