### ISSUE TITLE
What is the contribution level required to be listed as an author?

### ISSUE THREAD

**Issue by davidrpugh** [swcarpentry/python-novice-gapminder#407]
Just curious! I have had previous PRs merged into these lessons but never bothered to update the `AUTHORS` file myself as part of the PR. Thought a maintainer would do it when appropriate...

**Comment by alee** [comment]
We haven't really been keeping this up to date, sorry about that! I don't think any of us are on there either. 

That said, I think I'd prefer replacing it with a CONTRIBUTORS.md file that can be generated via make or travis, e.g.,  `make contributors` parses git metadata to get an ordered contributors list based on the authors. Something like https://allcontributors.org/docs/en/cli/usage or equivalent..

**Comment by vahtras** [comment]
A code snippet for this using invoke was presented at a pycon talk - try it out. make would be fine too

~~~
#tasks.py
from invoke import task
@task
def authors(c):
    r = c.run('git log --format="%aN <%aE>"', encoding="utf-8", hide=True)

    authors = set(r.stdout.splitlines())
    authors = sorted(authors)

    with open("AUTHORS", "w") as f:
        for author in authors:
            print(author)
            f.write(f"{author}\n")
~~~

~~~
$ invoke authors
A Lee <alee@users.noreply.github.com>
A. Flaxman <abie@alum.mit.edu>
Aaron O'Leary <aaron.oleary@gmail.com>
...
~~~

**Comment by brownsarahm** [comment]
For the releases, there's also a place to consent to inclusion and provide an orcid ID on AMY, it says anyone who contributed via PR.

**Comment by alee** [comment]
Thanks @brownsarahm ! @katrinleinweber sent a link to the discuss list earlier:

https://amy.carpentries.org/dashboard/trainee/autoupdate_profile/

@davidrpugh you may want to double check the *Do you consent to have your name or identity associated with lesson publications?* field and make sure it's set correctly..

**Comment by davidrpugh** [comment]
That was the problem! Sorted now. Thanks for pointing this out!
