### ISSUE TITLE
Data types diagram - submitted by email

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/python-novice-gapminder#408]
Find attached a diagram of the main data types present in Python (in .svg and .png format), which I'd like to add at the end of the "Data Types and Type Conversion" lesson in Plotting and Programming in Python. 

![diagram-carpentry](https://user-images.githubusercontent.com/19176319/58338687-d08bac80-7e0d-11e9-8b89-76be1e57db4e.jpg)

Note that this is actually an SVG file, not JPG.

**Comment by alee** [comment]
Thanks @ErinBecker ! Though I think the diagram didn't get uploaded properly, could you attach it to this issue directly?

**Comment by alee** [comment]
closing this issue in favor of #409
