### ISSUE TITLE
render python / code / output blocks

### ISSUE THREAD

**Issue by alee** [swcarpentry/python-novice-gapminder#418]
The python and output code blocks in the python-novice-inflammation lesson have nicely formatted headers:

http://swcarpentry.github.io/python-novice-inflammation/01-numpy/index.html

Are we missing some styling thing that's preventing our code blocks from being as shiny? 

http://swcarpentry.github.io/python-novice-gapminder/02-variables/index.html

summoning @maxim-belkin :tada:

**Comment by slel** [comment]
The different styling must originate in differences in the stylesheets. Compare:
- https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/assets/css/lesson.scss
- https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/assets/css/lesson.scss

**Comment by slel** [comment]
See this commit in particular:
- https://github.com/swcarpentry/python-novice-inflammation/commit/514fb469241fff95afaa44afe2c0551964879d92

**Comment by alee** [comment]
Thanks for the spelunking @slel !

**Comment by maxim-belkin** [comment]
Yes, you should merge gh-pages branch of the carpentries/styles repo.
```sh
git remote add styles https://github.com/carpentries/styles.git
git config --local remote.styles.tagOpt "--no-tags"
git fetch styles
git merge styles/gh-pages 
```
Then copy/paste (and add/commit) updated files from `/bin/boilerplate` into the main repo.

Apologies for the delayed response: was traveling, then teaching a workshop, then busy holidays.

**Comment by maxim-belkin** [comment]
@alee I can submit a PR that merges carpentries/styles and updates the files. Would you like me to do that?

**Comment by alee** [comment]
A PR would be great if not too much trouble, thanks @maxim-belkin ! Otherwise I'm happy to do it as well sometime tomorrow when I get back into the office.
