### ISSUE TITLE
Gapminder Formjacking Threats

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/python-novice-gapminder#419]
According to [Symantec](https://safeweb.norton.com/report/show?url=https://www.gapminder.org/&ulang=en), gapminder.org is currently compromised and contains several formjacking threats.  This lesson should probably have any direct links to the website removed until the threats can be resolved.

**Comment by alee** [comment]
Thanks for the heads up! Is it possible Symantec's analysis is flawed though? Google's safe browsing analysis doesn't turn up anything: https://transparencyreport.google.com/safe-browsing/search?url=gapminder.org&hl=en

Here's the symantec report for posterity - it's odd they include some jpg / png files, other URLs include the gapminder data visualization interfaces etc.

```
Threat Name: Web Attack: Formjacking Website 59
Location: https://static.gapminder.org/GapminderMedia/gapminder_world/sprite_navigation_03.jpg

Threat Name: Web Attack: Formjacking Website 59
Location: https://static.gapminder.org/GapminderMedia/gapminder_world/sprite_navigation_02.jpg

Threat Name: Web Attack: Formjacking Website 59
Location: https://static.gapminder.org/GapminderMedia/gapminder_world/sprite_navigation_01.jpg

Threat Name: Web Attack: Formjacking Website 59
Location: https://static.gapminder.org/GapminderMedia/wp-uploads/Screen-Shot-2013-10-17-at-10.22.02.png

Threat Name: Web Attack: Formjacking Website 59
Location: https://static.gapminder.org/GapminderMedia/wp-uploads/Screen-Shot-2013-10-16-at-22.31.29-1024x666.png

Threat Name: Web Attack: Formjacking Website 59
Location: https://static.gapminder.org/GapminderMedia/wp-uploads/Screen-Shot-2013-10-17-at-10.21.30.png

Threat Name: Direct Link To Web Attack: Formjacking Website 59
Location: https://www.gapminder.org/labs/gapminder-usa/

Threat Name: Direct Link To Web Attack: Formjacking Website 59
Location: https://www.gapminder.org/videos/dont-panic-the-facts-about-population/

Threat Name: Direct Link To Web Attack: Formjacking Website 59
Location: https://www.gapminder.org/world-classic/?use_gapminder_world'+n+'
```

The only reference to gapminder.org that I could find in the codebase is in setup.md - we could replace that with a link to the wikipedia page if we think this is serious enough: https://en.wikipedia.org/wiki/Gapminder_Foundation

**Comment by kekoziar** [comment]
Using a work computer that has a different level of security, when I go directly to the first image (...03.jpg), what is rendered in the browser is a html file with a script embedded.  
![gapminder-jpg-text](https://user-images.githubusercontent.com/28507641/59542680-e98ef700-8ebb-11e9-9ea7-82a70c3e3397.PNG)

**Comment by kekoziar** [comment]
I think the solution of directing to the Wikipedia page is good for now.  I'll see if I can find a contact number for the gapminder.org webmaster to let them know.

**Comment by alee** [comment]
Interesting.. that script appears in every 404 generated by static.gapminder.org e.g.,

`curl -O https://static.gapminder.org/foo.jpg` 

generates the same. Definitely looks suspicious!

**Comment by kekoziar** [comment]
Could be bad coding is throwing a false positive threat, but better safe than sorry!

**Comment by alee** [comment]
Agreed, thanks again for letting us know!
