### ISSUE TITLE
topic for the repository

### ISSUE THREAD

**Issue by dpshelio** [swcarpentry/python-novice-gapminder#448]
Please, consider adding a `lesson` topic to the repository. To do so you can [follow the help about how to add topics to the repository](https://help.github.com/en/articles/classifying-your-repository-with-topics). Check out the topics that the [Genomics R intro lesson](https://github.com/datacarpentry/genomics-r-intro) has gotten to add others that may be relevant to this lesson.

This will help people to know which repositories are lessons and also could be used to automate analysis of the repositories.

**Comment by alee** [comment]
Thanks for the tip @dpshelio! I don't believe the maintainers here have the permissions to edit these topics, so I think this is something to bring up with the @swcarpentry/lesson-maintainers or the maintainers of the styles repository.

See https://github.com/carpentries/lesson-infrastructure/issues/8 for some other context

**Comment by dpshelio** [comment]
Thanks for looking it up and point me to the right issue.

**Comment by fmichonneau** [comment]
Adding GitHub Topics is not within the scope of the GitHub permissions for Maintainers. We are coordinating an effort to standardize GitHub Topics across all our repositories. We are seeking input and feedback from Maintainers on the list of proposed topics. Please see the Request For Comments (RFC) in this GitHub issue: https://github.com/carpentries/maintainer-RFCs/issues/5
