### ISSUE TITLE
In "Programming Style": the last solution could be optimized

### ISSUE THREAD

**Issue by dungtran2612** [swcarpentry/python-novice-gapminder#458]
Hi all,

I found that in the solution for the last example in the lecture: [Programming Style](http://swcarpentry.github.io/python-novice-gapminder/18-style/index.html) could be optimized.

In the solution, function len(input_string) was called two times inside the  "for" loop. Even though in this example, the len() function might execute rapidly and the iteration of the loop is just 10, in other cases, It might not a lucky time. If the function is multiplications for floating-point numbers, and it was called inside a loop, it will take a long time to execute the code.

My suggestion, specifically for programmers who are at the beginning level, is to call the function outside the loop if it's possible. It is good behavior.

The original code:
` Calculate the len(input_string) in the for loop twice:
   
    old = input_string
    for i in range(iterations):
        new = ''
        # iterate through characters in previous string
        for j in range(len(input_string)):
            left = j-1
            right = (j+1)%len(input_string) # ensure right index wraps around
            if old[left]==old[right]:
                new += '-'
            else:
                new += '*'
        #print(new)
        # store new string as old
        old = new       `

The optimized code:
` pre-calculate the length outside the loop because the task doesn't depend on the loop.
    **len_s = len(input_string)** 

    len_s = len(input_string) 
    old = input_string
    for i in range(iterations):
        new = ''
        # iterate through characters in previous string
        for j in range(len_s):
            left = j-1
            right = (j+1)%len_s # ensure right index wraps around
            if old[left]==old[right]:
                new += '-'
            else:
                new += '*'
        #print(new)
        # store new string as old
        old = new       `

**Comment by alee** [comment]
This seems like a reasonable improvement to the code - would you like to submit a PR for this? The only suggestion I'd make is to make the variable `input_string_length` instead of `len_s`.

Thanks!

**Comment by neil-csiro** [comment]
Hi Folks,

First post here.  I'm a trainee and am following the checkout procedure link to good first issues and I see this near the top.  If it isn't impolite or bad etiquette, I intend to fork, edit and make a pull request as part of the checkout procedure.  I see the OP posted this weeks ago, and may possibly also be working on a fix now, but it seems to me like if you receive multiple fixes you can choose to integrate your favourite fix, so no harm done.  But let me know if it's inappropriate for me to do this.

Thanks,
Neil

**Comment by dungtran2612** [comment]
Hi Neil, 
This issue is also my checkout procedure. I am planning to do this weekend because of my tight schedule last week. I am a newbie so not sure you can create pull request based on current issue or need to make new suggestion. 
The best,
Dung.

**Comment by dungtran2612** [comment]
> This seems like a reasonable improvement to the code - would you like to submit a PR for this? The only suggestion I'd make is to make the variable `input_string_length` instead of `len_s`.
> 
> Oh, and if you are making changes there, making the code [PEP8 compliant](https://www.python.org/dev/peps/pep-0008/) would be great! This mostly has to do with spacing around operators and things but a number of our code samples have this same issue.
> 
> Thanks!

Hi Alee, 
Thank you for accepting my issue and thanks for your suggestion. Yes, definitely, I will use input_string_length instead of len_s.
Sorry for late response.
Dung Tran.

**Comment by neil-csiro** [comment]
Hi Dung,

Sorry - do make the edits and pop in the PR :)  It was marked as "help wanted" and "good first issue", but I'm unsure of how to interpret the tags with this asynchronous workflow.  I've just popped in a PR on a different issue that hopefully isn't conflicting with anybody else's work.

**Comment by dungtran2612** [comment]
Hi Neil, 
Thank you for your pull request. I should have done it earlier. I submitted this issue for my check out process, not pull request. So hopefully, it works for you. Good luck with your check out process.
