### ISSUE TITLE
"Writing Functions" - inconsistent question and solution formatting

### ISSUE THREAD

**Issue by stb2145** [swcarpentry/python-novice-gapminder#461]
I'd like to bring attention to the inconsistent formatting in the "Writing Functions" episode in the "Plotting and Programming in Python" lesson (http://swcarpentry.github.io/python-novice-gapminder/14-writing-functions/index.html). From a novice's perspective having a more consistent formatting when introducing questions and providing solutions would be very helpful - a simple fix would be to number the questions/solutions appropriately. 

Before I noticed that the question/answer formatting could be improved, I was struggling to understand what was trying to be explained in the "Order of Operations" block. In this case, numbering the questions and associated answers appropriately would've gone a long way in trying to understand what exactly was being asked and the solutions provided (perhaps the wording int he Q/A in this block could be more clear as well...).

The "Encapsulating Data Analysis" block has a very clear question-to-answer format where they are simply numbered in a consistent manner. As mentioned, a simple fix would be to follow that formatting throughout the episode!

**Comment by alee** [comment]
fixed in #514 - thanks @eldobbins !
