### ISSUE TITLE
Primes in lists examples

### ISSUE THREAD

**Issue by linajandren** [swcarpentry/python-novice-gapminder#468]
I find it problematic that the example for list.append() appends 9 to the lists of primes without noting that 9 is not, in fact, a prime number. (This is in the section "Appending items to a list lengthens it."
The lists examples following that addition still uses a list of primes including 9, even when using list.extend() to add even more primes.
The next section shows how to use del() to remove 9, but there is no note on why 9 was chosen to be removed.
It's possible you have discussed this earlier (I'm very new) but I would suggest the following:

Append just 7 in the first example. (Or, if for some reason it's considered necessary to add two elements, add 5 and 7.) Just leave out the 9 from the whole section on appending.
In the section "Use del to remove items from a list entirely." change the last two sentences before the code example to
"If an element should be removed from a list (in the example, 9 is not a prime number) we use del listtname[index] to remove the item and shorten the list.
del is not a function or a method, but a statement in the language."
Then go on to define primes = [2,3,5,7,9] and finally remove 9. 

I understand many people will find this self evident, but my experience is that a lot of people still wouldn't spot this. And I think it could be awkward for the instructor to teach this if someone in the audience is bothered by what seems like an error in the material. Sorry if I appear to be nitpicking :) just don't like errors in teaching material.

**Comment by mhagdorn** [comment]
I plan to work on this for my instructor checkout procedure - just in case someone else is thinking about claiming this issue.

**Comment by vahtras** [comment]
Thanks. I agree that in the first section it is not clear that 9 is a number that is entered by mistake, which we delete in the second section. These examples are not directly connected, so one could simply leave out 9 in the first example

**Comment by linajandren** [comment]
I see the changes have gone through, great job! This was the first time I raised an issue for a carpentries lesson so I'm not sure what proper etiquette would be. Do I close this issue now?

**Comment by vahtras** [comment]
You may close issues you have opened yourself, that is great, otherwise most often maintainers close issues.

**Comment by linajandren** [comment]
@vahtras thanks for letting me know. :) I'll close this, nothing really left to discuss since the offending number 9 is gone.
