### ISSUE TITLE
Briefly mention methods when using DataFrame.describe

### ISSUE THREAD

**Issue by charlesincharge** [swcarpentry/python-novice-gapminder#473]
Just taught this lesson to programming beginners, and they got tripped up on the different syntax of methods. It would help to have something like:
> Some data types have _methods_ associated with them, which are like functions that operate on the associated value. Methods are called similarly to a function with: <variable_name>.<method_name>(arguments)

When the first method (`DataFrame.describe`) gets used in https://swcarpentry.github.io/python-novice-gapminder/07-reading-tabular/index.html, there isn't a explicit mention of methods.

**Comment by aayux** [comment]
+1

Perhaps it would help to make a clear distinction made between data members and member functions before jumping into the examples.

Even without a complete understanding of classes or objects &mdash; and without getting into design philosophy &mdash;  it would be useful to know how the two constructs (data and methods/functions) differ. IMO a brief one or two line explanation should suffice.

**Comment by RMeli** [comment]
@charlesincharge @aayux Are you working on this issue or can I fix it as part of the checkout process?

**Comment by aayux** [comment]
It's fine by me. This has been open for a while and there are no PRs so I think it should be okay.

**Comment by charlesincharge** [comment]
@RMeli I'm not working on this actively. You/anyone else should feel free to fix this. Thanks!

**Comment by eldobbins** [comment]
I recently taught this, and included a brief intro to methods in Episode 4.  I used strings as an example because they are simple and have many methods associated with them.

I will submit a PR of what I did.
