### ISSUE TITLE
Lesson Contribution for Trainee

### ISSUE THREAD

**Issue by Talishask** [swcarpentry/python-novice-gapminder#474]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases I won't be able to follow up or provide more details other that what I'm providing below.

---
Hi,

As part of the checkout process for carpentries, it is encouraged that we provide feedback to one of the modules. Going through the Python Novice Mindgap section on lists, I noticed that when mentioning slices, it did not thoroughly go over inclusivity/exclusivity in slices.
![image](https://user-images.githubusercontent.com/45104071/81740382-e2c18900-946a-11ea-9b28-d0a12f8c6d03.png)

As slicing is a common implementation, for both novices and experts, I think it would be very helpful to have a few examples demonstrating how the first number provided is inclusive, and the last number is exclusive.

[This link](https://dev.to/duomly/what-is-slicing-in-python-58f2) provides a clear example of how this works, which can be easily included in the lesson.

**Comment by nishreenk** [comment]
Hey how can I be assigned this issue? I would like to work on this as a part of my Carpentries training checkout

**Comment by vahtras** [comment]
made @nishreenk assignee

**Comment by martinosorb** [comment]
I'd like to close this due to inactivity. The inclusivity of slice bounds is described when talking about strings in episode 2:

> We take a slice with the notation [start:stop], where start is the integer index of the first element we want and stop is the integer index of the element just after the last element we want.
> The difference between stop and start is the slice’s length.
