### ISSUE TITLE
translating the lesson into spanish

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/python-novice-gapminder#475]
Hello dear maintainers,

I'm Paula a carpentries volunteer for many years. I've taken many roles including, instructor, maintainer, trainer, liaison, translator, executive council members.

I wanted to get in touch with all of you to keep our newest project of translation aligned with your efforts. We will start translating this lesson in the next week. You can expect in the coming weeks that we might raise improvement suggestions if we find any. 

A similar effort has happened before you can see here: https://twitter.com/raynamharris/status/1070001633445130240?s=20

There's no actions required from your side. This is just an invitation to collaborate in discussions. I expect to close this issue once we complete the translation.

Thanks for your work maintening this lesson. Please tag anyone who might be interested in helping.

**Comment by alee** [comment]
Thanks @orchid00 !
