### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by nicoguaro** [swcarpentry/python-novice-gapminder#479]
In the lesson [Running and Quitting](https://swcarpentry.github.io/python-novice-gapminder/01-run-quit/index.html) in the section **Arranging Documents into Panels of Tabs**, I think that the word `then` is used instead of `them`

> First, create a text file, Python console, and terminal window and arrange then into three panels in the main work area. Next, create a notebook, terminal window, and text file and arrange then into three panels in the main work area. Finally, create your own combination of panels and tabs. What combination of panels and tabs do you think will be most useful for your workflow?

**Comment by vahtras** [comment]
Thanks, the typo has been fixed

Olav
