### ISSUE TITLE
explanation of plt.show() in python plotting

### ISSUE THREAD

**Issue by samumantha** [swcarpentry/python-novice-gapminder#482]
Hei,

in https://swcarpentry.github.io/python-novice-gapminder/09-plotting/index.html all the way in the bottom there is one mention of plt.show() in 'Saving your plot to a file'. Since the lesson is made for jupyter notebooks it is not really needed before. However, in the beginning of the module it is mentioned that the lesson can be taught using a regular interpreter as well. Since at that point, one needs the command plt.show() to see the plot; I would suggest to add maybe a box explaining what is the difference between plotting in jupyter and plotting without using jupyter, ie command line. Also that the command line waits for the popup plot to be closed again before going back to 'input mode' could be mentioned there. 

What do you think? Would this be helpful?

**Comment by vahtras** [comment]
Thank you for your suggestion! Actually, there are situations where plt.show is needed also in Jupyter, e.g. when you have two plot commands in the same cell and you want them in separate figures rather than the same figure. In any case, a brief  box  explaining the difference with command-line plotting may very well be useful.

**Comment by eldobbins** [comment]
I'm writing a PR for this.  I think original comment is referring to the ```plt.show(block=True)``` argument when discussing when control returns to the prompt.  I think that's a little far afield.  But I like the inclusion of generating multiple plots in a Notebook.

**Comment by vahtras** [comment]
Great!

Den lör 12 dec. 2020 20:08Liz Dobbins <notifications@github.com> skrev:
