### ISSUE TITLE
error in division types example

### ISSUE THREAD

**Issue by mhagdorn** [swcarpentry/python-novice-gapminder#492]
In lesson 3 type conversion example we have
```
num_subjects = 600
num_per_survey = 42
num_surveys = num_subjects // num_per_survey + 1
```
however when the the number of subjects is evenly divisible, eg when num_subjects = 42 we get one survey too many. The solution should be
```
num_surveys = (num_subjects + num_per_survey - 1) // num_per_survey
```

**Comment by alee** [comment]
Thanks for catching that! Would you be willing to submit a PR to fix this?

**Comment by mhagdorn** [comment]
In that paragraph there is also the description of the // operator: _In Python 3, the // operator performs integer (whole-number) floor division_
Here, _integer_ refers to the mathematical term of both positive and negative whole numbers rather than the python type integer which maybe a bit confusing since if you do a floor division where one of the operands is a float you get a float as well. So maybe it's better to describe it as:
... the // operator performs floor division, ie the result is rounded down to the nearest integer.
