### ISSUE TITLE
Reading Tabular Data - Numpy vs Pandas

### ISSUE THREAD

**Issue by ttimbers** [swcarpentry/python-novice-gapminder#5]
When reading in the Gapminder data, why not read it in with Pandas? That way the learners can easily see the column names, and you won't get into trouble loading the data because of the country column being a string in the datasets we are giving them (`np.loadtxt` throws a `ValueError: could not convert string to float: b'country'` when you try to use it to load `gapminder_gdp_americas.csv`).

I find Pandas more intuitive with the accessible column names and easy to view tabular-like data frames. Once it's loaded with Pandas, we can use Numpy functions to do the planned calculations. Thus, we don't have to get into all the Pandas nitty gritty.

**Comment by gvwilson** [comment]
Agreed - we'll use Pandas for this lesson, with a short aside on NumPy later on.
