### ISSUE TITLE
Going to a previous working directory in a terminal

### ISSUE THREAD

**Issue by awoonor** [swcarpentry/python-novice-gapminder#500]
As part of the instructor training checkout procedure, trainees are required to submit a small contribution to one of the carpentries lesson.

Going over the [Unix shell](http://swcarpentry.github.io/shell-novice/) lesson, the episode on [navigating files and directories](http://swcarpentry.github.io/shell-novice/02-filedir/index.html) provides a shortcut for moving up one directory level ("cd .."). In fact, this command is useful when one wants to access a previously visited directory in the folder tree. However, if one wants to access a previous folder/directory that is not directly one level up in the folder tree, this command does not achieve the intended task (or requires multiple iterations in order to work).

I think it would be useful to introduce the "cd -" command in the lesson, which is a shortcut for accessing a previously working directory in the terminal, irrespective of whether that directory is above or beneath your current working directory.

**Comment by alee** [comment]
I use `cd -` all the time to jump across directory hierarchies to the last working directory and think it's great! But did you mean to submit this issue to https://github.com/swcarpentry/shell-novice/issues instead?

**Comment by awoonor** [comment]
@alee, Yes, I meant to submit it to the shell novice GitHub page. Should I create a new issue on that page?

**Comment by slel** [comment]
@awoonor yes. Then add a comment here with a link to the issue there, and close.

**Comment by awoonor** [comment]
Issue resubmitted to https://github.com/swcarpentry/shell-novice/issues/1147.
