### ISSUE TITLE
updating Python setup instructions so that "check Add Anaconda to Path" is recommended

### ISSUE THREAD

**Issue by rbavery** [swcarpentry/python-novice-gapminder#501]
These setup instructions more clearly direct learners to add Anaconda to their PATH using the most recent language in the Anaconda installer: https://carpentries.github.io/workshop-template/

Versus the current instructions: http://swcarpentry.github.io/python-novice-gapminder/setup

Are the maintainers open to a PR that copies over the Python setup instructions from the workshop template, including the instructional video?

**Comment by alee** [comment]
That would be great! Apologies for the much delayed response

**Comment by vinisalazar** [comment]
Hi,

I submitted PR #545 that attempts to address this. I updated `setup.md` according to the workshop template instructions.

Best,
V
