### ISSUE TITLE
Lesson Contribution - Kernels not  "mentioned above"

### ISSUE THREAD

**Issue by klbarnes20** [swcarpentry/python-novice-gapminder#504]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

> 2. Python-novice- gapminder - plotting and programming with python
> Episode 1 - *http://swcarpentry.github.io/python-novice-gapminder/01-run-quit/index.html
> <http://swcarpentry.github.io/python-novice-gapminder/01-run-quit/index.html>*
> - Running and Quitting
>
Lists and describes the Kernel tab under the menu bar in JupyterLab. The
sentence - Actions for managing kernels which," as mentioned above", are
separate processes for running code - sounds incorrect as Kernels were
never mentioned or defined in prior sections of the document.

**Comment by alee** [comment]
good catch, we should have a brief blurb about Jupyter kernels - this could be as simple as lifting / lightly editing the description from https://jupyterlab.readthedocs.io/en/stable/user/documents_kernels.html#kernel-backed-documents

> In the Jupyter architecture, kernels are separate processes started by the server that run your code in different programming languages and environments. JupyterLab enables you to connect any open text file to a code console and kernel. This means you can easily run code from the text file in the kernel interactively.

**Comment by vinisalazar** [comment]
Hi,

I submitted the above PR that attempts to address this.

Best,
V
