### ISSUE TITLE
Lesson Contribution - Float division correction 

### ISSUE THREAD

**Issue by klbarnes20** [swcarpentry/python-novice-gapminder#505]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

> Episode 3 - *http://swcarpentry.github.io/python-novice-gapminder/03-types-conversion/index.html
> <http://swcarpentry.github.io/python-novice-gapminder/03-types-conversion/index.html>*
> - Types conversion. Data Types and Type Conversion.
>
The exercise, Division types, states that "However in Python2 (and other
> languages), the / operator between two integer types perform a floor (//)
> division. To perform a float division, we have to convert one of the
> integers to float.". This statement is inaccurate and should instead be
> "However in Python2 (and many other languages), the / operator between
> two integer types performs a floor (//) division. To perform a float
> division, we have to convert one of the integers to float." The statement
> is not true for all other languages e.g R and Perl.
>
If this issue is about a specific episode within a lesson, please provide its link or filename.

**Comment by alee** [comment]
should we remove references to Python 2 entirely? It has already been sunset.

**Comment by vahtras** [comment]
> should we remove references to Python 2 entirely? It has already been sunset.

I agree with this. It is time. A novice in our workshops should not have to encounter legacy forms of the language and removing these references will reduce  cognitive overload.
