### ISSUE TITLE
Lesson Contribution - Spaces after if statement 

### ISSUE THREAD

**Issue by klbarnes20** [swcarpentry/python-novice-gapminder#508]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

> Episode 13 - *http://swcarpentry.github.io/python-novice-gapminder/13-conditionals/index.html
> <http://swcarpentry.github.io/python-novice-gapminder/13-conditionals/index.html>*
> - Conditionals
>
As a good practice, The second if statement shouldn't contain a space after

**Comment by eldobbins** [comment]
Which line is this?  "if" is mentioned 20 times.
