### ISSUE TITLE
Americas-data.csv dataset not provided

### ISSUE THREAD

**Issue by AbrahamAvelar** [swcarpentry/python-novice-gapminder#511]
The "Conditionals" section uses the "Americas-data.csv" dataset which is not included in the  python-novice-gapminder-data.zip provided in the main page of the lesson. Please include it or change the last command box of this section.

**Comment by alee** [comment]
Thanks for catching that! I can't believe we've gone this long without running into this yet. I'll need to do some git spelunking to see if `files/python-novice-gapminder-data.zip` ever had `Americas-data.csv`.
