### ISSUE TITLE
Add directions for alt launching using anaconda-navigator

### ISSUE THREAD

**Issue by sstevens2** [swcarpentry/python-novice-gapminder#516]
The way the launching section is written now it sounds a bit like you can't launch a jupyter lab without using the terminal on a mac or jupyter prompt for windows. Might be good to offer alt directions for how you can launch it with anaconda navigator instead.  Learners often seem to prefer that option during the workshops I've taught.

**Comment by K-Meech** [comment]
I can add instructions for launching via anaconda navigator - I'll make a PR tomorrow!

**Comment by alee** [comment]
added in #533
