### ISSUE TITLE
Introduce list comprehensions after introducing lists and for loops

### ISSUE THREAD

**Issue by prtkm** [swcarpentry/python-novice-gapminder#52]
I was reading the plotting section (https://swcarpentry.github.io/python-novice-gapminder/10-plotting/) and found it seems to contain list comprehensions, e.g. 
```python
years = [col[-4:] for col in df.columns.tolist()]
```
The issue is that the section on creating lists and for loops seems to be after the plotting section. I think it makes more sense to move plotting so that it comes after lists.

**Comment by gvwilson** [comment]
Or remove the list comprehensions?  We want to get to plotting early, 
even if it's just for one data set, so that people have a payoff as 
quickly as possible.  But if we have to do a list comp to get the data, 
then yeah, move the plotting.  @montoyjh, what do you think?

**Comment by prtkm** [comment]
Another argument for moving lists before plotting is that plotting two lists against each other is so common (probably more so than plotting pandas dataframes ).

How about introducing lists first, then show how to plot two lists, then plot the "real" data from the csv file using the dataframe. We can remove the list comprehensions and maybe introduce it later when we talk about loops.

Ps. @montoyjh Weren't you in Jens/Aleksandra's group at Suncat?

**Comment by montoyjh** [comment]
Yes, in the last iteration of the workshop, we ended up covering lists before the pandas section, mostly because it ties in with loops.  That worked well, and I think we should consider making that change permanently.

However, the list comprehension here derailed the discussion a bit.  It may be fine to introduce those during the section on lists prior to pandas, or we could do a standard for loop to construct the list to remove list comprehension from the cog load.

**Comment by montoyjh** [comment]
@prtkm yep, I graduated last fall and began working at LBNL in Kristin Persson's group.

**Comment by gvwilson** [comment]
:+1: to rearranging the material if you feel it works better.

**Comment by tobyhodges** [comment]
+1 on rearranging. To me, putting lists before plotting makes sense, and list comprehensions are a useful but non-essential bonus. But the best way to find the right balance will be to teach the material, of course.

**Comment by gvwilson** [comment]
The original argument for plotting before lists was to give people 
something useful before lunch; looking at the schedule, this 
rearrangement will still accomplish that, so :+1: for the change. Who 
wants to do the PR?

**Comment by prtkm** [comment]
I can do the PR, I was going to do a PR for my instructor training checkout anyway.

How does lists > loops > pandas > plotting sound? That way the payoff is right before lunch...

**Comment by gvwilson** [comment]
:+1: - it'll involve renaming files (easy) and then checking that 
dependencies haven't been violated.  Please take out anything with list 
comprehensions; we can mention them in an exercise.
thanks much,
Greg

**Comment by prtkm** [comment]
See https://github.com/swcarpentry/python-novice-gapminder/pull/53

**Comment by prtkm** [comment]
I am closing this issue since the PR got merged.
