### ISSUE TITLE
Schedule in elapsed time instead of daytime?

### ISSUE THREAD

**Issue by RaphaelaHeil** [swcarpentry/python-novice-gapminder#571]
We recently faced the issue that learners were confused by the discrepancy between the workshop schedule (9 - 13) and the lesson schedule (9-16:30). Other Carpentries lessons (e.g. [The Unix Shell](http://swcarpentry.github.io/shell-novice/)) present the schedule as elapsed time (e.g. 0-4:30), which adds to the confusion, when teaching both in the same workshop.  

I am wondering, what the reason is behind the different schedule representation in this lesson? Would it be possible to adapt it to the style of the other Carpentries lessons?

**Comment by alee** [comment]
Thanks for raising this! I think it is legacy that was never cleared out, one of those details that we all live with until someone notices and lets us know 🥴 

I'll fix this shortly. Thanks again!
