### ISSUE TITLE
JupyterLab link broken on index.md

### ISSUE THREAD

**Issue by sborrego** [swcarpentry/python-novice-gapminder#594]
I just wanted to point out that the link for JupyterLab is broken on **line 10** in [index.md](https://github.com/swcarpentry/python-novice-gapminder/edit/gh-pages/index.md). It does not render correctly on the [webpage](http://swcarpentry.github.io/python-novice-gapminder/).

Hope this helps.

**Comment by alee** [comment]
Thanks for catching this @sborrego !
