### ISSUE TITLE
Move some material further up

### ISSUE THREAD

**Issue by danaikorre** [swcarpentry/python-novice-gapminder#599]
In the second episode I believe that it would be more usefull to have the sections "Python is case-sensitive" and "Use meaningful variable names" right after "Use variables to store values". It would keep all the information and instructions for using and allocating variables in one place before going into printing and slicing.

**Comment by vahtras** [comment]
Could make sense to review this, e.g. we a case sensitive example in the
initial section and later an independent section on case sensitivity...

**Comment by ldko** [comment]
I agree with doing this, moving case-sensitive stuff up to the top where it is all together and the meaningful variable names too is something I did the [last time I taught this lesson](https://ldko.github.io/python-novice-gapminder-short/02-variables/index.html#use-variables-to-store-values) (I had a shorter time frame to teach the material and was trying to condense it).

**Comment by milodubois** [comment]
As a boost of encouragement to @dsmanufacturing , @vahtras (and to play devil's advocate), regarding issue #599, for the course at [python-novice-gapminder](https://swcarpentry.github.io/python-novice-gapminder/), your point is spot on but the last iteration on gh-pages has an alert element saying "under design". When reading this and [lesson design](https://swcarpentry.github.io/python-novice-gapminder/design/), I am naturally included to be warned that the material may not be "production ready." In the interim, have you looked at https://github.com/swcarpentry/python-novice-inflammation which talks extensively about data types, syntax, etc., especially for those using Python for data science? (I offer my comment as a fellow in computational and molecular biology, with a prior focus on functional genomics, shifting now to epigenetics). Thanks to swcarpentry! Cheers!<br>  _Milo_

P.S., I will open a side issue about suggestions for NCI data sets that may be more relevant for those using swcarpentry learning tools.

**Comment by tmunker** [comment]
I agree it would be beneficial to extend the 'Use variables to store values' section with the two bullets from 'Python is case sensitive' or just bring that section forward. An argument for merging would be that the starting underscore naming convention is already named in 'Use variables to store values' and the starting capital naming convention is only mentioned in 'Python is case sensitive'. 

The example code in the 'Use meaningful variables names' section includes the print function, which is only explained after the first section, bringing it forward as is would thus likely result in confusion. In my opinion it would not detract from this section's intent to remove the print function example. On one hand it is good to remind the students to use meaningful variable names explicitly near the end of this episode, but I assume that in most courses this is one of the aspects that is repeated during the entire course by default.
