### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by linajandren** [swcarpentry/python-novice-gapminder#617]
The link for matplotlib.pyplot near the top of the page is broken. The link points to https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.html#module-matplotlib.pyplot but this gives me a page not found error. I'm not certain where the link should point, perhaps https://matplotlib.org/stable/tutorials/introductory/pyplot.html ?

**Comment by alee** [comment]
Thanks for letting us know! I think the link in Episode 9 (http://swcarpentry.github.io/python-novice-gapminder/09-plotting/index.html) used to go to a page like this: https://matplotlib.org/3.5.3/api/_as_gen/matplotlib.pyplot.html but I prefer your link as a more durable URL. 

We'd welcome a PR to correct the link in [episode 9](https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/_episodes/09-plotting.md), it'd be good to adjust all of those similar links if possible. I counted at least 4 of them there from a cursory grep. That matplotlib page is linked twice, once early on in the summary and again when introducing plotting via pandas dataframes, probably that second one could go away..?

- tick_params -> https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.tick_params.html
- savefig -> https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html

**Comment by alee** [comment]
Absolutely, I don't believe anyone else has put forward a PR or indicated they are up for working on this. Thanks @vhmcck !
