### ISSUE TITLE
Launching jupyter notebook using "jupyter notebook ."

### ISSUE THREAD

**Issue by SeanRGB** [swcarpentry/python-novice-gapminder#62]
This may just be my own ignorance but why do we launch the Jupyter notebook in the exercise (in 01-run-quit.md) with a trailing dot?

`$ jupyter notebook .`

Could we add a bullet point explaining that to the users? I would have added one myself but I sort of need someone to explain it to me...

**Comment by gvwilson** [comment]
Dot removed.
