### ISSUE TITLE
Pandas Link

### ISSUE THREAD

**Issue by stg7** [swcarpentry/python-novice-gapminder#621]
Dear all,
in python-novice-gapminder/_episodes/07-reading-tabular.md 
In the first section ("Use the Pandas library to do statistics on tabular data."), just a minor thing, I would propose adding a link to the Pandas library (https://pandas.pydata.org/), as it is also done in e.g. in https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/_episodes/08-data-frames.md for NumPy.

Best
Steve

**Comment by vahtras** [comment]
Thanks, that makes sense. Please suggest a change in a pull request

Regards
Olav
