### ISSUE TITLE
improve data frame names in the lesson

### ISSUE THREAD

**Issue by alee** [swcarpentry/python-novice-gapminder#628]
Creating an issue from #470 which was not merged but will be preserved in a new feature branch for the interim

The gist is we should use better variable names for data frames than `df` and `data`, and to explicitly provide descriptive names and explain why descriptive names are better in the lesson. These improved variable names should be threaded through all the episodes as well.

**Comment by sjvrijn** [comment]
With #631 merged, is there still anything left to do for this issue?

**Comment by alee** [comment]
Episodes 8 and 16 still have some residual `df` references that would benefit from renaming - a PR to fix those too for consistency would be very welcome!
