### ISSUE TITLE
Links not generated on Summary and Setup page

### ISSUE THREAD

**Issue by marklcrowe** [swcarpentry/python-novice-gapminder#634]
Paragraph 1 on Summary and Setup displays "This lesson references [JupyterLab][jupyterlab] ..." rather than JupyterLab being a link. 
Similarly, the final line of the Prerequisites immediately following this first paragraph displays "Please see [the setup instructions][lesson-setup] for more details."

**Comment by alee** [comment]
Thanks for catching those! We'll patch those soon, still figuring out the new workbench setup to render the lesson locally.
