### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by somet-code** [swcarpentry/python-novice-gapminder#648]
The "How to Contribute to an Open Source Project on GitHub" link in CONTRIBUTING.md is broken. Clicking on it leads to [404 - Page Not Found](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github), where a different link is suggested. The suggested link appears to be what you want.

I'm new to using GitHub, and since this seems like an issue that might affect many CONTRIBUTING.md files, I wanted to bring it to your attention before trying to proceed. Thank you!

**Comment by karenword** [comment]
Tagging @zkamvar because I *think* the current best place for issues like this might actually be https://github.com/carpentries/workbench . Can you confirm?

**Comment by vahtras** [comment]
Fixed the link in this repo
