### ISSUE TITLE
Error with "{:auto_ids} " 

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/python-novice-gapminder#658]
### What is the problem?

The [glossary section](http://swcarpentry.github.io/python-novice-gapminder/reference.html#glossary) begins with `{:auto_ids}`  which I am guessing is supposed to create ids and anchor links for each glossary item.  Instead the code itself displays and messes with the rendering of the first glossary item.   

### Location of problem (optional)

http://swcarpentry.github.io/python-novice-gapminder/reference.html#glossary

**Comment by alee** [comment]
Hmmm, the only references I can find to `auto_ids` in the swcarpentry org are in old Jekyll based code so maybe this is legacy Jekyll code that needs to be removed? I didn't see anything related to it in the [carpentries/workbench](https://github.com/search?q=org%3Acarpentries+auto_ids&type=code) either.

https://github.com/search?q=org%3Aswcarpentry%20auto_ids&type=code

**Comment by zkamvar** [comment]
> maybe this is legacy Jekyll code that needs to be removed?

Bingo.

**Comment by zkamvar** [comment]
In general, if you see anything that starts with `{:` or `{%`, it's Jekyll (or perhaps Hyde).

**Comment by alee** [comment]
Thanks for the report @maneesha !
