### ISSUE TITLE
motivating example

### ISSUE THREAD

**Issue by stuckyb** [swcarpentry/python-novice-gapminder#69]
This is the first of several issues I'm opening in response to Greg's request (03/07/16) for feedback on the lesson.  So, sorry for creating a bunch of new issues, but I think it's best to keep the topics separate.

So, first item: Perhaps this is still in the works, but I think some sort of motivating example at the very beginning would be useful.  A "Here's what you'll be able to do by the end of the day" sort of thing.  It's always good for students to be able to see where they are going, I think (and why).

**Comment by gvwilson** [comment]
The recent revision makes plotting the running (and motivating) example.
