### ISSUE TITLE
Exercise time estimates

### ISSUE THREAD

**Issue by tbekolay** [swcarpentry/python-novice-gapminder#7]
I really like the proposed outline in `index.md`! My only thought when reading through was that the morning exercises might take longer than estimated for a novice group, especially when we get to things like loading up Pandas dataframes and reading documentation.

Rather than extend the exercises and shift chunks around, I wonder if it would be better to take time from the teaching portion and shift it to the exercises. Or perhaps make the teaching / exercise split more flexible? E.g., for Built-in functions (and methods) and help, we could say Teaching + Exercises (10 min) but with a minimum of 5 minutes for exercises?

Just some brainstorms; it's hard to estimate how long challenges will take without seeing the challenges, so the time estimates might be way more appropriate to talk about later on down the line. The general pace of the lesson seems good to me!

**Comment by PBarmby** [comment]
I read through before I looked at Trevor's comments but I had the same thought: some of the timing in the earlier parts looked pretty tight to me.

**Comment by tobyhodges** [comment]
Looking through index.md I like the proposed content, and the order. But I agree that this is extremely ambitious to get through in a single day. I also would argue that starting from the beginning and stopping wherever you get up to by the end of the day would be dangerous. (Not suggesting that's your plan, just commenting.) 

We want people to leave knowing enough to follow the "Good Enough Practices" as you mention in the objectives - in my opinion the sections covering documentation, programming style, debugging, etc are the most valuable for this and what sets SWC apart from other tutorials available elsewhere/on the web.

So if you feel like you have to chuck something out, I vote against it being that stuff! Is it an option to just accept that it will take more than one day to take people from total beginner to Good Enough programmer?

**Comment by gvwilson** [comment]
Hi Toby,

I agree it will take people a lot more than one day to become a good 
enough programmer, but we only have one day in our workshop, and it only 
seems fair to learners to structure the lesson accordingly. So, what 
would you subtract?  The stuff from the end is obvious, but is there 
anything in the middle we can cut?  (Shaving a few minutes off every 
topic is tempting, but probably delusional...)

Thanks,
Greg

**Comment by tobyhodges** [comment]
Ok, I see your point.

If it were up to me, I'd reluctantly trim some of the data science stuff from the middle. If you can, shrink (but don't remove entirely) some of the pandas DataFrame, data loading, collective/summary operations, plotting etc. It's important that it's there because this is the stuff that will feel most relevant and exciting for a graduate level scientific audience. But I think that, if you ranked all of the material from most to least important with regards to learning good programming practices, these sections would be near the bottom.

**Comment by PBarmby** [comment]
I agree that the items Toby lists are not as important for learning good programming practice. But I think they have to be in there as motivation; the audience needs some reason to learn this stuff, and something that they can come back and practice on later -- their own data analysis is likely it.

Candidate topics to shorten (or even drop): data types, error messages, lists, programming with arrays (too much for beginner), defensive programming excet for DRY.

**Comment by gvwilson** [comment]
Addressed in #13.
