### ISSUE TITLE
remove unnecessary detail from 17-call-stack

### ISSUE THREAD

**Issue by stuckyb** [swcarpentry/python-novice-gapminder#72]
I fear there is way too much detail in 17-call-stack for "people who have never programmed before".  The key concept I would want my students to learn in this section is the idea of scope.  All of the information about the run-time stack, stack frames, etc. is low-level implementation details, and I doubt any of it is necessary.  I don't think a first-time programmer should have to worry about *how* scoping is implemented. The important thing is to understand what it means.

**Comment by gvwilson** [comment]
Closed by cbc29d0
