### ISSUE TITLE
02-variables Add comment to age example

### ISSUE THREAD

**Issue by willingc** [swcarpentry/python-novice-gapminder#74]
In http://swcarpentry.github.io/python-novice-gapminder/02-variables/:

It would be helpful to add a comment to the ``age = age + 3`` example that ``# Earlier in this notebook we assigned age to 42`` or ``# age = 42 was assigned earlier in this lesson``.

Distance away from initial assignment as well as novice learners may be confused otherwise.

**Comment by gvwilson** [comment]
Closed by fddebcf
