### ISSUE TITLE
01-Running - formatting and starting off 

### ISSUE THREAD

**Issue by beroe** [swcarpentry/python-novice-gapminder#75]
(There is a formatting glitch in the `~~~` for running the notebook. Needs to be on a new line? Also not clear to a total newcomer whether you type the `$`) 

If this is for people who have never programmed before, I found the organization and beginning really confusing: "Python programs are plain text files" Now let's talk about using Jupyter which stores scripts as JSON. 

Maybe there needs to be a lesson zero, which talks about gathering the commands they have typed into the python interpreter into a text file and running them as scripts. Then the current 01 could be called something about using Jupyter, and it could do the same thing in there?

It is redoubled by the fact that they go back to interpreter-like interactions with basic assignments, and not running scripts within a notebook.

**Comment by gvwilson** [comment]
Formatting glitch fixed - the intention is to use the Jupyter Notebook throughout (no command-line lessons).
