### ISSUE TITLE
Collected comments

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/python-novice-gapminder#8]
It is a really nice outline! Here are a few comments.

### Goals

Not all are treated in the lesson it appears, e.g. 

> f. Dependencies and requirements are explicit (e.g., a requirements.txt file)
> i. Submit code to a reputable DOI-issuing repository upon submission of paper

In
> c. Programs of all kinds (including "scripts") are broken into functions that:

the subitems from "Good Enough Practices in Scientific Computing" are missing.

### Running and Quitting Interactively

Perhaps reverse the order: first show that the cell you have is a python cell. Then add that one can have markdown cells as well - in the hope of reducing confusion

### Variables and Assignment

>Trace behavior of swapping (a, b = b, a the old fashioned way) with an intermediate variable

I think I understand the idea, but it is not entirely clear from the description

### Looping Over Data Sets

>  (use glob to get filenames)

This will require som explanation if learners do not know unix (but it is not impossible)

**Comment by gvwilson** [comment]
Thanks - addressed in 69ba176097.
