### ISSUE TITLE
Lots of broken external links in lesson materials

### ISSUE THREAD

**Issue by jstaf** [swcarpentry/python-novice-gapminder#80]
Almost all of the of the external links for this lesson that I've tried clicking on so far seem to be broken:

For instance, the link to the gapminder dataset in the [setup instructions](http://swcarpentry.github.io/python-novice-gapminder/setup/) points to http://swcarpentry.github.io/python-novice-gapminder/setup/python-novice-gapminder-data.zip, when it should instead point to https://github.com/swcarpentry/python-novice-gapminder/raw/gh-pages/python-novice-gapminder-data.zip.

Here's another example - all of the sites in the [Next Steps](http://swcarpentry.github.io/python-novice-gapminder/21-next-steps/) segment seem to point at the GitHub pages site  instead of the actual external websites at (scipy for example points at http://swcarpentry.github.io/python-novice-gapminder/21-next-steps/scipy.org instead of http://scipy.org/).

**Comment by gvwilson** [comment]
Whoops - thanks Jeff, that's a build bug.  I'll try to fix it over the 
weekend.

**Comment by jstaf** [comment]
Ok, sounds good!

Out of curiosity, would you say this lesson is "ready to teach" yet, or should I stick with the older "inflammation" materials? I was going to be doing a Software Carpentry Python lesson in two weeks and although I've practiced with the other materials, I like the content of this one a lot more (it explains the topics better and introduces things in a more logical order). Would I be making things harder for myself if I went with the new lesson?

**Comment by gvwilson** [comment]
It hasn't been taught yet in this form, but we're keen to have people 
alpha-test and let us know how it goes.  In particular, if you want to 
try it out and report back on how long the episodes actually take, we'd 
be very grateful.  Where's the workshop?

**Comment by jstaf** [comment]
The workshop is a bit of a non-standard format- we're wrapping 4 days of Software Carpentry content into our summer school in Ottawa this year (we decided it would be very useful to add basic computing workshops instead of teaching advanced HPC topics only).

Our "Software Carpentry" website is here: https://cac-staff.github.io/summer-school-2016/
