### ISSUE TITLE
Strings to Numbers exercise (ep 03)

### ISSUE THREAD

**Issue by biologyguy** [swcarpentry/python-novice-gapminder#84]
I wonder if it's not better, in episode 03, to demonstrate how recasting will break on cases that they should be expected to break on before giving a task at that will throw an exception.
See the changes suggested in commit 113b92cbfc58e4ce6a5e6e7eabbacec67810595c to see what I mean.

**Comment by gvwilson** [comment]
Sure - can you please submit a short PR that does this?

**Comment by biologyguy** [comment]
Done and done.
Pull request #109
