### ISSUE TITLE
Strings to Numbers exercise errors

### ISSUE THREAD

**Issue by upendrak** [swcarpentry/python-novice-gapminder#85]
In the[ 3rd chapter](http://swcarpentry.github.io/python-novice-gapminder/03-types-conversion/) of the python introduction, i noticed that the following errors

> print("string to float:", float("3.4"))
#### The result of this should be 
> string to float:, 3.4
#### and not
> 3.4

Similarly
> print("float to int:", int(3.4))
#### The result of this should be
> float to int:, 3
#### and not
> 3

Thanks
Upendra

**Comment by gvwilson** [comment]
A pull request to fix this would be very welcome - thanks.

**Comment by upendrak** [comment]
Will do

**Comment by barrachri** [comment]
This issue should be closed by this PR https://github.com/swcarpentry/python-novice-gapminder/commit/6670116485d71f0947d3af678ecfb3f387ae308b

But the output is still not correct, it should be:

print("string to float:", float("3.4"))
print("float to int:", int(3.4))
string to float: 3.4
float to int: 3

I will do a PR to fix this.

**Comment by barrachri** [comment]
PR: https://github.com/swcarpentry/python-novice-gapminder/pull/105
