### ISSUE TITLE
Docstrings in python

### ISSUE THREAD

**Issue by upendrak** [swcarpentry/python-novice-gapminder#86]
Can we introduce the concept of Docstrings in Python and how useful they are. I see that the docstrings have been used in several places throughout the lessons but never talked about Docstrings anywhere.

**Comment by gvwilson** [comment]
a pull request would be very welcome - thanks!

**Comment by upendrak** [comment]
Will do

**Comment by upendrak** [comment]
Actually, there is a mention of Docstrings in [here](http://swcarpentry.github.io/python-novice-gapminder/20-style/). I'm sorry i did not noticed that.
