### ISSUE TITLE
From setup, link to data is broken

### ISSUE THREAD

**Issue by justbennet** [swcarpentry/python-novice-gapminder#89]
On the setup page

http://swcarpentry.github.io/python-novice-gapminder/setup/

the linke to the data under Getting the Data is to

http://swcarpentry.github.io/python-novice-gapminder/setup/python-novice-gapminder-data.zip

which returns a 404 Not Found.  The file appears to be at

https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/python-novice-gapminder-data.zip

**Comment by gvwilson** [comment]
Fixed in fd5ddd393a
