### ISSUE TITLE
possible midterm exam

### ISSUE THREAD

**Issue by PBarmby** [swcarpentry/python-novice-gapminder#9]
Looking at what's covered in the morning, I was going to suggest something similar to what's in the python-novice-inflammation lesson: loop over a set of datafiles and for each one, read data, extract a subset, calculate something, plot something else. This seems awfully ambitious for people who haven't programmed before, however - but maybe for motivated folks it's feasible.

**Comment by gvwilson** [comment]
If it seems ambitious for our intended audience, it probably is. Where 
would you think we could get most people, in most workshops? (It'll be 
interesting to compare markers...)

Cheers,
Greg

**Comment by PBarmby** [comment]
Wild guess: could make it to "Collective Operations" by mid-way.

**Comment by IanHawke** [comment]
I think a group with minimal technical problems could get to the loop over datafiles by the midpoint; if there were hiccups, then the "Collective Operations" seems a reasonable point. In that case they could be asked to select and normalize multiple subsets, which could lead into the looping section to come after the break.
